### ISSUE TITLE
configure script, makefile?

### ISSUE THREAD

**Issue by haroldopsf** [AravisProject/aravis#101]
I'm trying to build the project on Ubuntu 16.04. I do not see a configure script nor a makefile in the source. What am I missing?
"
user@lucile:~/gitws$ git clone https://github.com/AravisProject/aravis
Cloning into 'aravis'...
remote: Counting objects: 8953, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 8953 (delta 0), reused 1 (delta 0), pack-reused 8947
Receiving objects: 100% (8953/8953), 4.66 MiB | 1.79 MiB/s, done.
Resolving deltas: 100% (6774/6774), done.
Checking connectivity... done.

user@lucile:~/gitws$ cd aravis/

user@lucile:~/gitws/aravis$ ./configure
bash: ./configure: No such file or directory

user@lucile:~/gitws/aravis$ make
make: *** No targets specified and no makefile found.  Stop.

"
Thanks for any help

**Comment by EmmanuelP** [comment]
./autogen.sh

**Comment by barzan-hayati** [comment]
> ./autogen.sh

`./configure` and `make` worked for me. but  `./autogen.sh` didn't work for me.

**Comment by EmmanuelP** [comment]
@barzan-hayati  `autogen.sh` is for development purpose only. If you don't intend to work on aravis itself, just use the release tarballs from ftp.gnome.org, and configure the build with `./configure`.
