### ISSUE TITLE
Build issue with current GIT master branch

### ISSUE THREAD

**Issue by nerian-vision** [AravisProject/aravis#104]
I'm unable to build the current revision due to an undefined reference to
`arv_gc_p_value_indexed_node_new`

In arvgcvalueindexednode.c, there is a definition of `arv_gc_value_indexed_node_new` (without the _p). So I assume this should be renamed?

**Comment by EmmanuelP** [comment]
Could you attach the build log, please ?

Did you try to run autogen.sh ?

**Comment by EmmanuelP** [comment]
No update, old report. I'm closing this issue. Please reopen if you have the requested informations.

Thanks.
