### ISSUE TITLE
arv-viewer unable to supply a video stream for a FLIR A6604

### ISSUE THREAD

**Issue by NicoleSickelmore** [AravisProject/aravis#110]
My colleagues and I have been trying to get a video stream from a FLIR A6604. When we try to view the image stream using the viewer, we get a blank screen. The test and other cameras work perfectly.  Can you please advise whether or not our camera is supported? If not, what would the next step be?

**Comment by EmmanuelP** [comment]
Please attach the output of `arv-tool-0.6 features`.

**Comment by EmmanuelP** [comment]
No update, old report. I'm closing this issue. Please reopen if you have the requested informations.

Thanks.
