### ISSUE TITLE
Why does the 0.5.10 release build bins like`arv-tool-0.6`?

### ISSUE THREAD

**Issue by greyltc** [AravisProject/aravis#114]
https://github.com/AravisProject/aravis/blob/6b2fa462a6fd432adea5d132d280cce29579a5f1/configure.ac#L18

Should the API version match the release version?

**Comment by EmmanuelP** [comment]
0.5 releases are part of a development serie. 0.6 releases will be stable ones.

Hence the use of 0.6 for the API versions during 0.5.x.

**Comment by greyltc** [comment]
Got it, thanks!
