### ISSUE TITLE
Building with --enable-viewer on macOS fails due to Mac GTK not including X11

### ISSUE THREAD

**Issue by evanmtp** [AravisProject/aravis#120]
When trying to build Aravis with ./configure --enable-viewer on macOS 10.12, it fails with the following error:

arvviewer.c:27:10: fatal error: 'gdk/gdkx.h' file not found

This is probably because GTK+3 installed on macOS via the Homebrew package manager excludes the X11 backend, which gdkx.h is part of. [See this thread for more info](https://apple.stackexchange.com/questions/205404/how-can-i-get-gdk-x11-3-0-on-os-x). Other projects have faced this issue, [e.g. Go-GTK](https://github.com/mattn/go-gtk/pull/248). Would it be possible for the Aravis viewer to use Quartz instead of X11 when building on Mac?

**Comment by EmmanuelP** [comment]
591acc43a14059a11d20456f32b3ce57be483326 should make the compilation pass. But I don't know if the corresponding bineray works fine on OSX. Please reopen if you still have an issue.
