### ISSUE TITLE
Sen Tech STC-SB152POE Issue

### ISSUE THREAD

**Issue by walberts** [AravisProject/aravis#121]
Hello, I have been testing with a SenTech camera and the video is just display as a black screen. Looking at the wire shark packets they appear to be empty. I also have attached a wire shark file from a connection with the provided viewing software and the video is working. I am working through some other build issues with my project and i will look at the issue when i get a chance.

[pelora camera test.zip](https://github.com/AravisProject/aravis/files/1540897/pelora.camera.test.zip)

**Comment by walberts** [comment]
Issue was with Ethernet interface on the host. SenTech camera is working.

**Comment by EmmanuelP** [comment]
Great to know. Thanks.
