### ISSUE TITLE
UV stream thread loses sync with the device when there is no destination buffer available

### ISSUE THREAD

**Issue by TIS-Tim** [AravisProject/aravis#126]
After applying my proposed patch for issue #125, the situation can arise that there are no buffers available for arv_uv_stream_thread to copy data to.

If arv_stream_pop_input_buffer returns NULL, the thread stays in the state where it expects a leader, while the device sends image data.

Because the payload data is larger than the requested size for the leader, libusb then reports LIBUSB_TRANSFER_OVERFLOW, which, according to its documentation, should be avoided.

I think only asking for a leader to be transferred if a buffer is available to be filled would be a solution to avoid this situation.

**Comment by EmmanuelP** [comment]
> I think only asking for a leader to be transferred if a buffer is available to be filled would be a solution to avoid this situation.

That was the previous situation. I have fixed the issue by requesting a maximum transfer size when we are waiting for a leader. Thanks a lot for the report.

Cheers.
