### ISSUE TITLE
Command line to save file of one snapshot

### ISSUE THREAD

**Issue by anusornl** [AravisProject/aravis#137]
I just installed Aravis 0.5.11 in my computer with Scientific Linux 7. I would like to ask if there is a command line to save file of one snapshot. It will be useful to my research.

**Comment by EmmanuelP** [comment]
There is no such tool, sorry.

But if you have compiled aravis with gstreamer support, you should be able to construct a gstreamer pipeline that does what you want.

You could also try to extend tests/arvacquisitiontest.c to actually do something with the acquired buffer.
