### ISSUE TITLE
Under which license is Aravis published?

### ISSUE THREAD

**Issue by tglander** [AravisProject/aravis#138]
The file COPYING contains the GPL license, i.e., a copyleft license which prohibits use of Aravis without also publishing derived code.
However, the README.md states that "Aravis is released under the LGPL v2+", which is a permissive license allowing derived to be closed source.
Which license is it?

**Comment by EmmanuelP** [comment]
https://github.com/AravisProject/aravis/blob/d0c7ff2083d9abc22b70f4874cdad73c66cd99b8/COPYING#L1
A proprietary software can be linked to the aravis library.
Any distribution of a modified binary version of aravis must give access to the corresponding source code.

**Comment by tglander** [comment]
Thanks for clarifying. So it is GPL2, not LGPL.v2+. You might want to update the README.md to make it consistent.

**Comment by EmmanuelP** [comment]
No. Gnu **L**ibrary **G**eneral **P**ublic **L**icense.

This is the v2 version. Headers say the code is licensed under the v2 or any later version. Hence v2+.
