### ISSUE TITLE
Changing frame rate disables trigger mode

### ISSUE THREAD

**Issue by TIS-Edgar** [AravisProject/aravis#142]
Hi Emmanuel,

What is the intention behind disabling trigger mode when changing framerates?
When calling `arv_camera_set_frame_rate` both "TriggerSelector" and "TriggerMode" are set to default values (in the case of TIS cameras). 
Since trigger mode is independent of the stream settings I would have expected that changes to frame rate, resolution etc. are possible without losing this setting.

Am I overlooking something or can this be changed?

**Comment by EmmanuelP** [comment]
I don't know. You should ask to 2013 Edgar:

https://github.com/AravisProject/aravis/commit/8d9c974f40d14ea42f36c89faa01bf3579e32b81#diff-00227b92d9261a01842630ba7382d941R631

More seriously, set_frame_rate is not just for setting the frame rate feature, but also for configuring a constant frame rate based acquistion. Which means the trigger must be set correctly to achieve a constant frame rate stream after acquisition_start is called.
