### ISSUE TITLE
arv_device_get_*_feature_bounds not wrapped in python properly

### ISSUE THREAD

**Issue by eudoxos** [AravisProject/aravis#146]
Methods querying feature bounds take min/max value as `gint64*`, the GObject-Introspection expects plain pointers, since the function is not annotated (https://github.com/AravisProject/aravis/blob/master/src/arvdevice.c#L464); this is also apparent from Aravis-0.6.gir:

      <method name="get_integer_feature_bounds"
              c:identifier="arv_device_get_integer_feature_bounds">
        <return-value transfer-ownership="none">
          <type name="none" c:type="void"/>
        </return-value>
        <parameters>
          <instance-parameter name="device" transfer-ownership="none">
            <type name="Device" c:type="ArvDevice*"/>
          </instance-parameter>
          <parameter name="feature" transfer-ownership="none">
            <type name="utf8" c:type="const char*"/>
          </parameter>
          <parameter name="min" transfer-ownership="none">
            <type name="gint64" c:type="gint64*"/>
          </parameter>
          <parameter name="max" transfer-ownership="none">
            <type name="gint64" c:type="gint64*"/>
          </parameter>
        </parameters>
      </method>

Annotations should be added to those function to make them accessible from Python.

(Sorry for the dry tone. I am very grateful for Aravis. Thanks a lot.)

**Comment by EmmanuelP** [comment]
I have just pushed a fix to master. Most of ArvDevice is still not annotated though. Patches welcome !

Thanks for the report.
