### ISSUE TITLE
Instructions on how to contribute with translations

### ISSUE THREAD

**Issue by josephgbr** [AravisProject/aravis#15]
[Damned Lies](https://l10n.gnome.org/module/aravis/) send translators to Aravis wiki to look for instructions on how to submit translations, but there is no instructions in there. It would be nice to have some information specifying if one should open an issue attaching PO file, create a pull request etc.

**Comment by EmmanuelP** [comment]
Hi Joseph,

I have created a wiki page which explains how to contribute translations. Please let me know if you think it is not detailed enough.

**Comment by josephgbr** [comment]
Did you published somewhere? I wasn't able to find it.

**Comment by EmmanuelP** [comment]
https://github.com/AravisProject/aravis/wiki/Translations

**Comment by josephgbr** [comment]
Looks good. However Damned Lies points to [https://wiki.gnome.org/Projects/Aravis](https://wiki.gnome.org/Projects/Aravis). How about (also?) add such information in there?

**Comment by EmmanuelP** [comment]
Done.

**Comment by josephgbr** [comment]
Thanks!
