### ISSUE TITLE
Aravis typelib not being installed

### ISSUE THREAD

**Issue by ChaosCA** [AravisProject/aravis#163]
I'm having issues installing on Ubuntu 16.04. I was able to build with the following commands:
```
./configure --enable-viewer --enable-gst-plugin --enable-introspection=yes
make
sudo make install
sudo ldconfig
```

All of which resolved without issues. However no typelib file was created(as it should have been) inside /usr/lib/girepository-1.0.

I need the typelib for Aravis python bindings..

Thanks

**Comment by ChaosCA** [comment]
After a successful install I now get errors when trying to `make`.

```
arvuvcp.c: In function ‘arv_uvcp_packet_type_to_string’:
arvuvcp.c:127:29: error: ‘ARV_TYPE_UVCP_PACKET_TYPE’ undeclared (first use in this function)
  return arv_enum_to_string (ARV_TYPE_UVCP_PACKET_TYPE, value);
                             ^
arvuvcp.c:127:29: note: each undeclared identifier is reported only once for each function it appears in
arvuvcp.c: In function ‘arv_uvcp_command_to_string’:
arvuvcp.c:133:29: error: ‘ARV_TYPE_UVCP_COMMAND’ undeclared (first use in this function)
  return arv_enum_to_string (ARV_TYPE_UVCP_COMMAND, value);
                             ^
arvuvcp.c: In function ‘arv_uvcp_packet_type_to_string’:
arvuvcp.c:128:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
arvuvcp.c: In function ‘arv_uvcp_command_to_string’:
arvuvcp.c:134:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:913: recipe for target 'arvuvcp.lo' failed
```

**Comment by EmmanuelP** [comment]
Hi,
> After the successful install 

Successful install of what ?

Which version of aravis do you try to install ? Please use the tarballs hosted here: http://ftp.acc.umu.se/pub/GNOME/sources/aravis/

If the issue persists, please attach the complete install log here.

**Comment by ChaosCA** [comment]
This project. I used the latest tarball and ran the commands I gave above. The first time I tried it seemed to complete fine but now I get the error I posted above.

**Comment by EmmanuelP** [comment]
Sorry, but you did not answer to my question: which version of aravis are you using ?
Did you try to ip your installation, and restart ?

**Comment by arbustoadamo** [comment]
@ChaosCA  How did you get to fix the error? The same thing has happened to me since 3 days ago.
