### ISSUE TITLE
Timestamp jump in the past

### ISSUE THREAD

**Issue by YarochkinMichael** [AravisProject/aravis#168]
Hello, Emmanuel

I am using MatrixVision camera (BC-x104eC)
Timestamp is included in chunk data. That is how i am extracting it:
currentTimestamp = arv_chunk_parser_get_integer_value(streamAravis->GetParser(), buffer, "ChunkTimestamp");

After changing exposure time of the camera this value is jumping in the past: previousTimestamp < currentTimestamp.
Also it is happening once in a while during acquisition.

Here is log file. There you can see "currentTimestamp" and "previousTimestamp - currentTimestamp"
[timedif 2.txt](https://github.com/AravisProject/aravis/files/2062598/timedif.2.txt)

If i  am using SDK from Mv it is not happening.

Can you help me to find the reason, please?

Mikl

**Comment by EmmanuelP** [comment]
Hi Mikl,

Could you try to modify your software and also display the frame id, timestamp and system_timestamp returned by arv_buffer_get_frame_id, arv_buffer_get_timestamp and arv_buffer_get_system_timestamp, and attach the result here ?

**Comment by YarochkinMichael** [comment]
Hello, Emmanuel

Sorry. It was bug in our firmware.
Aravis is working fine. Thank you.

Mikl

**Comment by EmmanuelP** [comment]
No problem.

Cheers.
