### ISSUE TITLE
The image is not captured after unpluging and pluging back the camera unless I run gstream launch

### ISSUE THREAD

**Issue by azmosavi** [AravisProject/aravis#169]
I'm working with aravis 6 and whenever I unplug the camera and plug it back, I'm not able to capture any image unless I run the script "gst-launch-1.0 tcambin serial=....". 
My image width and height are 1280 and 960. The payload size is 1228800.

When I put it in the debug mode, unplugging and plugging back the camera, I get:
[GvStream::finalize] n_completed_buffers    = 0
[GvStream::finalize] n_failures             = 107
[GvStream::finalize] n_timeouts             = 107
[GvStream::finalize] n_aborteds             = 3
[GvStream::finalize] n_underruns            = 0
[GvStream::finalize] n_missing_frames       = 0
[GvStream::finalize] n_size_mismatch_errors = 0
[GvStream::finalize] n_received_packets     = 219
[GvStream::finalize] n_missing_packets      = 60027
[GvStream::finalize] n_error_packets        = 0
[GvStream::finalize] n_ignored_packets      = 0
[GvStream::finalize] n_resend_requests      = 0
[GvStream::finalize] n_resent_packets       = 0
[GvStream::finalize] n_duplicated_packets   = 0
[Stream::finalize] Flush 1 buffer[s] in input queue
[Stream::finalize] Flush 4 buffer[s] in output queue

When I run the gstream script, I get every things normal:
GvStream::finalize] n_completed_buffers    = 51
[GvStream::finalize] n_failures             = 0
[GvStream::finalize] n_timeouts             = 0
[GvStream::finalize] n_aborteds             = 1
[GvStream::finalize] n_underruns            = 0
[GvStream::finalize] n_missing_frames       = 0
[GvStream::finalize] n_size_mismatch_errors = 0
[GvStream::finalize] n_received_packets     = 174800
[GvStream::finalize] n_missing_packets      = 0
[GvStream::finalize] n_error_packets        = 0
[GvStream::finalize] n_ignored_packets      = 0
[GvStream::finalize] n_resend_requests      = 239
[GvStream::finalize] n_resent_packets       = 239
[GvStream::finalize] n_duplicated_packets   = 0
[Stream::finalize] Flush 4 buffer[s] in input queue
[Stream::finalize] Flush 1 buffer[s] in output queue

Any idea what might cause this issue and when running that gstream script, what it is 
actually fixing?

**Comment by EmmanuelP** [comment]
tcambin gstreamer element is not part of the aravis source code. Please report your issue to The Imaging Source.
