### ISSUE TITLE
Take 10 more ms to get the frame

### ISSUE THREAD

**Issue by zuoyefen** [AravisProject/aravis#175]
Hi sir,  compared to 5.09, the 5.12 version will take 10 more ms to get the frame. Camera is U3 type(MindVision, height:600, width:600).

**Comment by EmmanuelP** [comment]
There is little difference between the two release in arvuvstream.c. Please try to rerun your test with ARV_DEBUG set to 'sp:3'.

**Comment by EmmanuelP** [comment]
No answer, I'm closing this issue. Please reopen if you have the requested information.
