### ISSUE TITLE
aravis GStreamer plugin doesn't load with GStreamer 1.14.x

### ISSUE THREAD

**Issue by AusMatt** [AravisProject/aravis#185]
The plugin is built but gst-inspect-1.0 blacklists it.
Testing with aravis 0.5.13.
Configure args: --enable-usb --enable-viewer --enable-gst-plugin --disable-gtk-doc-html
It loads fine with built with GStreamer 1.12.5.
Testing on Ubuntu 16.04.5 LTS x86_64

**Comment by EmmanuelP** [comment]
It should be fixed in master since 0f66b9748d69416baa74b3a1c712c982113e3d79.

**Comment by AusMatt** [comment]
I can confirm that the plugin is no longer blacklisted if I build aravis from the head of git master.
I've successfully used gst-inspect1.0 to inspect the aravissrc element.

**Comment by EmmanuelP** [comment]
Thanks for the confirmation.

Cheers.

**Comment by thinkski** [comment]
Did this regress? With gstreamer 1.14.1 (from Ubuntu 18.04.1 LTS universe) and aravis-0.6.0 release (`3891b1a`) again is blacklisted.

**Comment by AusMatt** [comment]
Chris,

I've had no problem with Aravis 0.6.0 and GStreamer 1.14.2.
Maybe you need to remove your GStreamer plugin registry cache?
rm ~/.cache/gstreamer-1.0/registry.x86_64.bin
Note that the plugin is now called "aravis" and the element is called
"aravissrc".

Matt

**Comment by thinkski** [comment]
Thanks Matt, it was even simpler than that — had to `export GST_PLUGIN_PATH=/usr/local/lib/gstreamer-1.0`.
