### ISSUE TITLE
FLIR Blackfly S chunk payload type

### ISSUE THREAD

**Issue by thecaptury** [AravisProject/aravis#189]
Hi,

I just enabled chunk mode for a Blackfly S camera and the payload type of the images was 0x10005 rather than the expected ARV_GVSP_PAYLOAD_TYPE_CHUNK_DATA==0x0004.

So the check in arv_buffer_get_chunk_data() that checks for the correct buffer type fails. However, if that check is relaxed from
`	g_return_val_if_fail (buffer->priv->gvsp_payload_type == ARV_GVSP_PAYLOAD_TYPE_CHUNK_DATA, NULL);
`
to
`	g_return_val_if_fail (buffer->priv->gvsp_payload_type == ARV_GVSP_PAYLOAD_TYPE_CHUNK_DATA || buffer->priv->gvsp_payload_type == 0x10005, NULL);
`
everything works as expected.

Interestingly, wireshark claims that payloadtype is 16 bit while aravis uses 32 bit.
https://www.wireshark.org/docs/dfref/g/gvsp.html
So maybe the upper 0x10000 is actually part of a different field. Actually this
https://github.com/wireshark/wireshark/blob/master/epan/dissectors/packet-gvsp.c (line 1133 ff)
seems to indicate that for the extended_chunk_data there are some flag fields before the payload type in the leader.

Should I fix the leader and prepare a pull request?
nils

**Comment by EmmanuelP** [comment]
Hi Nils,

> Should I fix the leader and prepare a pull request?

Yes, please.

Cheers.
