### ISSUE TITLE
No image on viewer with FLIR A6261sc

### ISSUE THREAD

**Issue by PrimordialKangaroo** [AravisProject/aravis#195]
Camera is detected by the viewer, but no matter which pixel format chosen, hitting play results in no change to the viewer, the camera selection screen remains as an artifact.
This is a genicam using ethernet.

EDIT: adding the debug output.
[A6261sc.txt](https://github.com/AravisProject/aravis/files/2403142/A6261sc.txt)

**Comment by EmmanuelP** [comment]
Could you attach the output of: `./tests/arv-camera-test -d all` ?

**Comment by EmmanuelP** [comment]
And also attach a screenshot of the viewer window.

**Comment by EmmanuelP** [comment]
I'm clsing ths report. Please reopen when you have the requeste informations.

Cheers.
