### ISSUE TITLE
IDS UI-3290SE USB 3.1 Camera not Detected

### ISSUE THREAD

**Issue by vanthome** [AravisProject/aravis#202]
Hi, my camera [UI-3290SE](https://en.ids-imaging.com/store/ui-3290se.html) does not get detected. Should this even work? I don't know whether it is "genicam" based.
BG and thanks

**Comment by EmmanuelP** [comment]
This is an USB 3, and IDS does not advertise it as an USB3Vision camera, which means it is not supported by aravis.

Cheers.
