### ISSUE TITLE
Payload size for WRITEMEM commands

### ISSUE THREAD

**Issue by coachcal43** [AravisProject/aravis#208]
https://github.com/AravisProject/aravis/blob/c937a133e35405aa9c7e00d64b00af790659aea5/src/arvgvdevice.c#L267

Is there a reason why the WRITEMEM commands always write payload data in blocks of sizeof(guint32)? I'm trying to send a writemem command to my device, and when I specify a data length of 5 bytes the code line above rounds it to the nearest guint32 size; thus, it writes a command of length 8 bytes instead of 5. If I modify the aravis '_write_memory' function in the following way, to pass the 'size' that I specify, then I receive a successful response:

    packet = arv_gvcp_packet_new_write_memory_cmd (address, size,
						       0, &packet_size); 

I'm using a similar setup to that listed in issue #179 -- i.e. sending commands to Pleora iPORT CL-GigE Cameralink->GigE Vision framegrabber->gige-converter (https://www.pleora.com/products/frame-grabbers/iport-cl-gige/)

**Comment by EmmanuelP** [comment]
I have just checked to not round the write memory payload size to 4 byte words with a bunch of cameras I have.
Unfortunately, it doesn't work with one of them (a Smartek GC1281XM).
I have searched for a register that would indicate if the rounding is necessary, but did not find one. So I guess it is mandatory.
