### ISSUE TITLE
arv-example returning payload value of 0

### ISSUE THREAD

**Issue by winstonliu** [AravisProject/aravis#21]
Camera model: Teledyne Genie Nano C1940 (G3-GC10-C1940)
Using aravis-0.4

`arv_camera_get_payload` is returning 0 when `arv-example` is run.

`buffer_count` is running smoothly at 30 Hz, but the buffer sizes are all 0.

Please find the Genie XML file attached (generated from `arv-tool-0.4 -n <camera name> genicam`).

[Teledyne_Nano.txt](https://github.com/AravisProject/aravis/files/518129/Teledyne_Nano.txt)

**Comment by EmmanuelP** [comment]
The IntSwissKnife node used for payload size computation is using Expression nodes, which are not supported yet by aravis.

**Comment by winstonliu** [comment]
Okay, thanks!

**Comment by EmmanuelP** [comment]
Should be fixed by 277c6218b941b1ffae85efd5410199c0eff2e530.
