### ISSUE TITLE
[Question] should I retrieve the buffer in stream callback?

### ISSUE THREAD

**Issue by wuyuanyi135** [AravisProject/aravis#218]
Hi,
I noticed in the examples and tests, you retrieve the frame buffer in the emitted g_signal callbacks. I am not familiar with glib and decide to put the buffer pop and push job in the stream callback. Also, you mentioned emitting signals can cause performance issues. 
Can you elaborate the different way of handling the buffer?

**Comment by EmmanuelP** [comment]
Using glib signals is more convenient when you are used to glib programming, but it has a performance impact.
Apart from the performance issue, both ways (signal or callback) are similar. They happen in the same thread as the data packet receiving code, so you have to take care to not block for too long, or data loss may happen (It is probably more critical in the GigEVision case).
There is a third way to retrieve buffers, that helps to avoid the blocking of the data receiving thread, which consists in polling for incoming buffers from the main thread (or another one you have created) using the arv_stream_pop/push buffer API, like what is done here: https://github.com/AravisProject/aravis/blob/eb552ab349928a1b130cf64c2b689c9a023ad2ca/tests/arvchunkparsertest.c#L39

Cheers.

**Comment by wuyuanyi135** [comment]
That helps. Thank you!
