### ISSUE TITLE
arv_camera_abort_acquisition leaves unreleased buffer.

### ISSUE THREAD

**Issue by wuyuanyi135** [AravisProject/aravis#221]
I am memchecking my app with Valgrind. I found that `arv_camera_abort_acquisition` will cause memory leak of an unreleased `ArvBuffer`. I think PR #193 may addressed this problem that the current buffer may not be properly destroyed when finalizing the stream.

My current workaround is to put the allocated buffers in somewhere and check whether any unreleased after the stream gets `g_object_unref`ed.

**Comment by EmmanuelP** [comment]
Fix merged.
