### ISSUE TITLE
Need an example how to guard the device object in callback

### ISSUE THREAD

**Issue by wuyuanyi135** [AravisProject/aravis#226]
Hi,
I have read that the library requires some locks for accessing the thread-unsafe device object in the callbacks. 
```
A possible trap is that glib signal callbacks are called from the thread that emitted the corresponding signal. For example, the "new-buffer" callback is emitted from the stream packet receiving thread, which is an internal thread created by ArvGvStream. It is not safe to use ArvDevice and some ArvStream functions from this callback without using mutexes. The exceptions are #arv_stream_push_buffer, #arv_stream_pop_buffer, #arv_stream_try_pop_buffer and #arv_stream_timeout_pop_buffer.
```
I am looking into calling `arv_camera_stop_acquisition` and finalization code in the `ArvStream` `ARV_STREAM_CALLBACK_TYPE_BUFFER_DONE` callback. Destroying the stream within the stream callback is not possible because it triggers the deadlock of pthread waiting self. However, I tried to create a new thread in the `ARV_STREAM_CALLBACK_TYPE_BUFFER_DONE` callback to stop acquisition, yet it still got stuck at https://github.com/AravisProject/aravis/blob/183af8734fe309fb0d1e854fb27e239a9418f728/src/arvuvstream.c#L388. 

I wonder which mutex should I acquire before I can stop the camera and release the stream? Do I have to unref the allocated objects in the same thread or I missed something to do it in a new thread?

Thanks

**Comment by EmmanuelP** [comment]
Hi,

You should destroy the stream in the thread that created the stream. You may use a GCond and call g_cond_signal from the stream callback, and use g_cond_wait_until in the thread that created the stream. A simple boolean variable could also to the trick.

Cheers,

Emmanuel.
