### ISSUE TITLE
Change installation process to add/update link to latest lib version

### ISSUE THREAD

**Issue by ArkadiuszRaj** [AravisProject/aravis#23]
I mean instead of placing aravis-0.x... files only there shall be a symbolic link named 'aravis' pointing to most recent version of lib and headers. This will make life easier a bit :)

**Comment by EmmanuelP** [comment]
Oh no, that defeats the point of parallel installable versions.

Going from aravis-0.2 to aravis-0.4 is not just a matter of a recompilation. API and ABI is different in different stable series.

By the way, API and ABI can also change during the development period. It is currently happening in the 0.5.x development serie.
