### ISSUE TITLE
properly usage of arv_make_thread_realtime

### ISSUE THREAD

**Issue by rickvavilin** [AravisProject/aravis#231]
How to use arv_make_thread_realtime properly? If I call arv_make_thread_realtime from main thread, only main thread becomes realtime, but I need make realtime internal ArvStream thread.
![_247](https://user-images.githubusercontent.com/3637079/52397329-e384a600-2ad6-11e9-8044-8a9ed35bf1dd.png)

**Comment by EmmanuelP** [comment]
Hi Rick,

You can change the realtime priority of the stream receiving thread in the stream callback. Please have a look at tests/arvcameratest.c here: https://github.com/AravisProject/aravis/blob/39d58e1295fb3505809eeac1b371f9da946a9d08/tests/arvcameratest.c#L178-L190 and here: https://github.com/AravisProject/aravis/blob/39d58e1295fb3505809eeac1b371f9da946a9d08/tests/arvcameratest.c#L340

Cheers,

    Emmanuel.

**Comment by rickvavilin** [comment]
It's great! Thanks!
