### ISSUE TITLE
Cross compilation for ARM using GigE camera and Aravis

### ISSUE THREAD

**Issue by payala07** [AravisProject/aravis#245]
Hello,
My issue is the following, I'm using a camera Basler acA1300-30gm alongside with Aravis. It works well on the local system and also while calling from a different network using uniscast. On the next step of my experiment I require to cross compile Aravis in order to use on an ARM system (modified armv7l).
Using the configure file :
![este es el que anda](https://user-images.githubusercontent.com/48588622/57302302-2ad10180-70db-11e9-8726-52de2bf6e281.PNG)
I didn't have any problem creating the executables:
![file_arvcameratest](https://user-images.githubusercontent.com/48588622/57302364-4dfbb100-70db-11e9-996a-0a5f517494d1.PNG)
The problem though is that, to be able to make it run on the ARM system I required it to be ELF 32-bits instead of ELF-64 bits. The following is the error given:
![error_v1](https://user-images.githubusercontent.com/48588622/57302696-0f1a2b00-70dc-11e9-94c6-70a0dccdd839.PNG)
![error_v2](https://user-images.githubusercontent.com/48588622/57302709-16d9cf80-70dc-11e9-9202-565d25085913.PNG)
![error_v3](https://user-images.githubusercontent.com/48588622/57302718-1d684700-70dc-11e9-8686-09065e0c3ad6.PNG)
If I try cross-compiling exclusively the arv-camera-test after the ./configure worked, I get the following error:
![crosscompath_v1](https://user-images.githubusercontent.com/48588622/57302964-9c5d7f80-70dc-11e9-82c0-8670a2ee8498.PNG)
arm-buildroot-linux-uclibcgnueabi-gcc: /root/root/aravis/lib/libaravis-0.6.a: No such file or directory
In file included from /root/aravis/include/aravis-0.6/arvtypes.h:30,
                 from /root/aravis/include/aravis-0.6/arv.h:28,
                 from arvacquisitiontest.c:1:
/root/aravis/include/aravis-0.6/arvenums.h:30:25: error: glib-object.h: No such file or directory
...
And other compilation errors that otherwise do not appear.
Is there any version of Aravis that allows me to create the executables under that format? or is a problem of changing the cross compiling path giving all the shared libraries? 
In the case that it can be worked with an static library, could you upload the c file of libaravis-0.6 please?
I thanks you in advance for your help.

**Comment by EmmanuelP** [comment]
Hi,

I have almost no experience in cross compilation. All I know is the cross compilation setup can be tricky to get it working. If possible, I would try to compile natively on the target platform.

**Comment by payala07** [comment]
Hello, 
Thanks for your answer Emmanuel, yes, it is indeed quite tricky. So far I was able to fix most of the compilation errors, but it is no perfect yet, so far the library that is stopping it, is related to the time stamp. I will leave here what I did, in case anyone is in a similar spot.
![image](https://user-images.githubusercontent.com/48588622/57628914-24d79680-759b-11e9-9a7a-2f7374668a22.png)
![image](https://user-images.githubusercontent.com/48588622/57629006-4df82700-759b-11e9-94f2-cb04de498641.png)
Some of the compilation errors:
![image](https://user-images.githubusercontent.com/48588622/57629078-72ec9a00-759b-11e9-8095-93c8edb8e6e7.png)
![image](https://user-images.githubusercontent.com/48588622/57629113-8861c400-759b-11e9-929f-e6bcb5e57ec3.png)

Cheers,
Paola.

**Comment by payala07** [comment]
Hello, 
Correcting the line for the cross-compilation:
![image](https://user-images.githubusercontent.com/48588622/57693800-6a06d180-764a-11e9-8ce1-42cb587dd62e.png)
That corrects the compilation errors leaving only this one:
![image](https://user-images.githubusercontent.com/48588622/57693869-8a369080-764a-11e9-9ca4-014ea31adde6.png)
Cheers,
Paola.

**Comment by payala07** [comment]
Hello, I made some progress although i'm still stuck. The compiler path for the cross-compilation is the following:
![image](https://user-images.githubusercontent.com/48588622/58406872-e34eed00-806a-11e9-90d5-a9fa79765227.png)
However, I still got problems with the linker:
![image](https://user-images.githubusercontent.com/48588622/58406941-037eac00-806b-11e9-9fbe-d479e01c4e7d.png)
If anyone got an idea of how to solve it, I will be more than thankful.
Cheers,
Paola.

**Comment by payala07** [comment]
Hello, some news in the topic, using a Makefile I was able to go around some of the configuration errors, but still have a problem with the linking.
![image](https://user-images.githubusercontent.com/48588622/58476223-757cf100-8150-11e9-8916-ca7240c2432c.png)
If someone have some insight, I will be really thankful.
Cheers,
Paola.
P.d.: Here is the Makefile.
[Makefile.txt](https://github.com/AravisProject/aravis/files/3227491/Makefile.txt)

**Comment by payala07** [comment]
Hello there, I got some updates:
changing the Makefile for the cross-compiler a little bit:
[Makefile.txt](https://github.com/AravisProject/aravis/files/3231749/Makefile.txt)
the files compiles and links:
![image](https://user-images.githubusercontent.com/48588622/58546785-66f11100-8206-11e9-878a-89fc1ff16274.png)
![image](https://user-images.githubusercontent.com/48588622/58546815-7a03e100-8206-11e9-87b0-3db2bcad703b.png)
However it stills generates two problems:
- /root/armel/usr/lib/arm-linux-gnueabi/libc.a(dl-tsd.o)(.text+0x18): R_ARM_TLS_LE32 relocation not permitted in shared object
-:tests/test_paola/arv_acquisition_test # ./arv-acquisition-test
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault                                                                                       
I know that the first error is due to the contrast in between -static and -shared, however I do not know from where comes the second error. If someone have any idea how to solved it, I will be really grateful.
Cheers,
Paola

**Comment by payala07** [comment]
Hello,
I verified it with some colleagues, under the current system this is as far that the cross-compilation goes. It is able to compile, link and generate executable but due to the custom system, the previously mentioned errors appears due to incompatibility.
I will clean up the Makefile for it nevertheless (after cleaning it), it might be of some use for those who are trying to cross-compile Aravis elsewhere.
Cheers,
Paola
