### ISSUE TITLE
Meson version unnecessary too high

### ISSUE THREAD

**Issue by ArkadiuszRaj** [AravisProject/aravis#251]
Ubuntu 18.04 LTS has meson in 0.45.1 version.
But Aravis' mason.build requests version >=0.47.0

I suggest lowering needed rev to 0.45 as it is enough to compile current Aravis

```
diff --git a/meson.build b/meson.build
index 78d50b9..aae1170 100644
--- a/meson.build
+++ b/meson.build
@@ -1,4 +1,4 @@
-project ('aravis', 'c', 'cpp', version: '0.7.0', meson_version: '>=0.47.0')
+project ('aravis', 'c', 'cpp', version: '0.7.0', meson_version: '>=0.45.0')

 gnome = import('gnome')
 i18n = import ('i18n')

```

**Comment by EmmanuelP** [comment]
Hi Arek,

Aravis actually requires 0.47:

```
WARNING: Project specifies a minimum meson_version '>=0.45.0' but uses features which were added in newer versions:
 * 0.47.0: {'copy arg in configure_file'}
```

Recent version of meson should be easy to install on any distribution using pip. I have bumped the requirement lately to suppress a warning in the way I was using configure_file() in viewer/data/meson.build

Anyway, I would accept a patch that removes the use of copy arg and lower the meson requirement, as long as no warning is emitted during meson configuration.

Cheers.
