### ISSUE TITLE
Aravis - Driver support

### ISSUE THREAD

**Issue by manukharshan** [AravisProject/aravis#262]
Hi,

We are planned to use Aravis library for "BLACKFLY S FLIR P/N: BFS-PGE-31S4, GIGE VISION" camera. We want to know whether we could use aravis library for Blackfly S.

Thanks and Regards,
Manu

**Comment by EmmanuelP** [comment]
Hi,

Aravis is supposed to support most of the GigEVision devices, but there is no authoritative list of supported devices. You may want ot ask on the aravis mailing list, where there is a better chance you get an answer.

aravis@freelists.org

Cheers.
