### ISSUE TITLE
Missing check for dependency

### ISSUE THREAD

**Issue by abrock** [AravisProject/aravis#277]
I built it on Debian stretch and it failed:

> [74/127] Generating Aravis-0.8.gir with a custom command.
> FAILED: src/Aravis-0.8.gir 
> /usr/bin/g-ir-scanner --no-libtool --namespace=Aravis --nsversion=0.8 --warn-all --output src/Aravis-0.8.gir -DARAVIS_COMPILATION -I/home/cnc/aravis/src -I/home/cnc/aravis/build/src --filelist=/home/cnc/aravis/build/src/25a6634@@aravis-0.8@sha/Aravis_0.8_gir_filelist --include=GObject-2.0 --include=Gio-2.0 --symbol-prefix=arv_ --identifier-prefix=Arv --pkg-export=aravis --cflags-begin '-DGETTEXT_PACKAGE="aravis-0.8"' -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libxml2 -I/usr/include/libusb-1.0 --cflags-end --library aravis-0.8 -L/home/cnc/aravis/build/src -lglib-2.0 -lgobject-2.0 -lgio-2.0 -lxml2 -lz -lm -laudit -lusb-1.0
Couldn't find include 'GObject-2.0.gir' (search path: '['/home/cnc/.local/share/flatpak/exports/share/gir-1.0', '/var/lib/flatpak/exports/share/gir-1.0', '/usr/local/share/gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0', '/usr/share/gir-1.0']')
[76/127] Compiling C object 'tests/59830eb@@evaluator@exe/evaluator.c.o'.
ninja: build stopped: subcommand failed.

I installed the package libgirepository1.0-dev and now it builds, perhaps the "meson build" could check for the presence of the package/file?

**Comment by EmmanuelP** [comment]
I think it is a debian packaging issue. On fedora, glib2 gir files are provide by gobject-introspection-devel, which is a dependency of meson.

For higher level dependency, like gtk3, gir files are in the gtk3-devel package, which also provides the pkgconfig file.

There is nothing I can do in aravis, and  after a quick search, it looks like no other software built using meson try to do more than what does aravis.

I'm closing this issue. Thanks for the report. Don't hesitate to reopen if you think there is something we can do in aravis.

Cheers.
