### ISSUE TITLE
Document porting from 0.6 to 0.8 (1.0 ?)

### ISSUE THREAD

**Issue by EmmanuelP** [AravisProject/aravis#281]
The next stable release will probably be Aravis 1.0. I'm currently reviewing the API and make some corrections before the API freeze. That means API breaks happen:

- [x] arv_device_set_*_feature_value functions take a GError
- [x] device_get_status moved to ArvCamera

**Comment by llschloesser** [comment]
Relatedly, are there release notes? I have not found them. If there are, I think a more prominent link placement on the markdown page would be nice.

**Comment by EmmanuelP** [comment]
@llschloesser I have added a link to the NEWS file in README.
