### ISSUE TITLE
IDS Camera UI-5240FA not found

### ISSUE THREAD

**Issue by Axel13fr** [AravisProject/aravis#282]
Hi there,

I was wondering if this driver shall work with this GigE camera https://fr.ids-imaging.com/store/ui-5240fa.html ?

I tried using it and I can correctly ping it but arv-tool says there are no device found. Are there any other limitations or specifics ?

Thanks in advance!

**Comment by EmmanuelP** [comment]
Hi Axel,

There is no mention of GigeVision nor Genicam on the product description page. It is most probably not compatible with aravis.

Cheers,

    Emmanuel.

**Comment by Axel13fr** [comment]
Thanks a lot for the feedback.

Le ven. 30 août 2019 à 09:54, Emmanuel Pacaud <notifications@github.com> a
écrit :
