### ISSUE TITLE
Add meson option to toggle tests

### ISSUE THREAD

**Issue by lovesegfault** [AravisProject/aravis#286]
I am packaging Aravis to Gentoo, and noticed that tests are always built. Since this is not necessary, not everyone who wants to install Aravis also wants to test it, I'd like to ask that a meson option be added to toggle test compilation.

Thank you!

**Comment by EmmanuelP** [comment]
I'm not sure how useful it is, but I will accept a patch that adds conditional test compilation.

**Comment by EmmanuelP** [comment]
Should be fixed by 22c48eb8582312105689149f356278093da5fb91
