### ISSUE TITLE
Meson install step is incomplete

### ISSUE THREAD

**Issue by lovesegfault** [AravisProject/aravis#292]
Packaging Aravis for Gentoo I came across a couple issues which ended up requiring the following hack in the ebuild
```
	# Aravis appends the major and min versions (but not the patch) to it's
	# binaries and it's folder in /usr/share. Things then end up like
	# `arv-tool-0.6`. We use this little hack to find out the version of the
	# current build in a way that works even for a live ebuild.
	local install_pv="$(ls ${ED}/usr/share | grep aravis- | cut -f 2 -d '-')"
	local install_p="${PN}-${install_pv}"

	# Properly place icons
	if use viewer; then
		cp -r "${ED}/usr/share/${install_p}/icons" "${ED}/usr/share" || die "Failed to copy icons"
	fi

	# Symlink versioned binaries to non-versioned
	dosym "arv-tool-${install_pv}" "usr/bin/arv-tool"
	dosym "arv-fake-gv-camera-${install_pv}" "usr/bin/arv-fake-gv-camera"
	use X && dosym "arv-viewer-${install_pv}" "usr/bin/arv-viewer"
```

The issues are that:
1. Icons are not placed in the correct location, and need to be manually copied there. They should be placed in `$prefix/usr/share/icons`
2. Binaries have version numbers suffixed to their names, but this doesn't match the `Exec` line in their `.desktop` counterparts. Either install them without the suffix, or add the suffix to the `Exec` line in the `.desktop` files.

**Comment by EmmanuelP** [comment]
Hi Bernardo,

Which version of aravis are you trying to package ?

Meson in aravis 0.6 is not the default nor recommended build system.

**Comment by lovesegfault** [comment]
@EmmanuelP Uh-oh, Aravis 0.6 is packaged using meson on Gentoo. When is 0.7 (or 0.8?) or the next version with full/proper meson support going to/is expected to be released?

**Comment by EmmanuelP** [comment]
The first unstable release of the 0.7 serie should happen within a month. I will try to release a 0.8 version (perhaps 1.0) at the end of this year, but without any guarantee.

I'm closing this report, aravis 0.6.x should be built using autotools. Don't hesitate to reopen if you have issues with aravis 0.7 and meson.

**Comment by lovesegfault** [comment]
Thanks Emmanuel!
