### ISSUE TITLE
(arv-viewer: ): Aravis-WARNING **: Failed to make stream thread high priority

### ISSUE THREAD

**Issue by EasitMickly** [AravisProject/aravis#327]
Hi, i build the source files and it success, but i run the program and it shows (arv-viewer): Aravis-WARNING **: Failed to make stream thread high priority. I don't know how to slove this problem, please help me. Thank you.

**Camera description:**
 - IMI-Tech
 - IMB-711G
 - GIGE

**Platform description:**
 - 0.6 and 0.7
 - Ubuntu 18.11 LTS ARM64
 - Jeson nano

![1](https://user-images.githubusercontent.com/48611092/71552087-93853980-2a30-11ea-980f-2098b96e1f79.png)

**Comment by AntonioMichaelAlvarez** [comment]
Try to add `cap_sys_nice` permission to arv-viewer executable:
```
sudo setcap cap_sys_nice+ep $(which arv-viewer)
```
This will allow rtkit (or whatever Aravis uses) to increase thread priority.

**Comment by EmmanuelP** [comment]
@EasitMickly , did @AntonioMichaelAlvarez advice help you fix your issue ?

**Comment by EmmanuelP** [comment]
I'm closing this issue. Please reopen if you have additional informations.

Cheers.
