### ISSUE TITLE
Implement Visibility property

### ISSUE THREAD

**Issue by madamczyk7ce** [AravisProject/aravis#331]
As is written in the title the idea is to implement getting Visibility property from a node. I think it'll be a useful feature.

> I guess the Visibility property could be used, but it is not implemented in Aravis. Please open a GitHub issue.

The beginning of this topic started in "Loading GenICam nodes to camera" issue in the Aravis forum.
https://aravis-project.discourse.group/t/loading-genicam-nodes-to-camera/62

**Comment by EmmanuelP** [comment]
Fixed by f95a22f0d2d10b4dc8d5661b677ae8d65270c378
