### ISSUE TITLE
arv-fake-gv-camera: support Bayer pixel formats

### ISSUE THREAD

**Issue by lovesegfault** [AravisProject/aravis#354]
**Is your feature request related to a problem? Please describe.**
I have some code that expects to stream a camera, using Aravis, and to receive bayered frames that it then de-bayers and outputs BGR. I wanted to write some tests for that piece of code using `arv-fake-gv-camera` but I found that I cannot set the pixel format to BayerRG8 as I desired.

**Describe the solution you'd like**
I'd like for `arv-fake-gv-camera` to support Bayer pixel formats for testing code that expects to have to demosaic images.

**Comment by EmmanuelP** [comment]
Hi Bernardo,

That would be a nice to have feature.

If you know how to generate a bayer test image, it should be trivial to add to arvfakecamera.c.

**Comment by lovesegfault** [comment]
@EmmanuelP Would I just need to hook the bayer pattern generator in here?
https://github.com/AravisProject/aravis/blob/b537efc2e86b4d2adf134bc135ebff5560a4a444/src/arvfakecamera.c#L530

**Comment by EmmanuelP** [comment]
Yes, and add an entry in arv-fake-camera.xml here:

https://github.com/AravisProject/aravis/blob/b537efc2e86b4d2adf134bc135ebff5560a4a444/src/arv-fake-camera.xml#L220

**Comment by lovesegfault** [comment]
How are those values determined?

**Comment by EmmanuelP** [comment]
https://www.emva.org/wp-content/uploads/GenICamPixelFormatValues.pdf
https://www.emva.org/wp-content/uploads/GenICam_PFNC_2_3.pdf

**Comment by lovesegfault** [comment]
I have a prototype working, will make a PR soon:
![image](https://user-images.githubusercontent.com/7243783/81490698-c825bf00-9274-11ea-882e-05f5c16ea366.png)

**Comment by Rz-Rz** [comment]
I wonder if this is possible to change the pixel depth to 10 for this use case ? i.e. using bayerrg10 ? Would love to implement it if feasible
