### ISSUE TITLE
gst pipe for flir chameleon usb camera

### ISSUE THREAD

**Issue by laszlopazonyi** [AravisProject/aravis#361]
I did installed aravis 0.6.4 on ubuntu 18.04.
arv-viewer works fine and I can get the video stream just fine.
I really need help from you to find the gst pipe, how to get video stream from the camera and possibly use that gst pipe in an other app on same machine. this camera is not a v4l. (I hope I am correct on that)
falcon@falcon-GB-BRi7-H-8550:~/aravis-0.6.4$ lsusb
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 006: ID 1e10:3300 Point Grey Research, Inc. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 8087:0029 Intel Corp. 
Bus 001 Device 003: ID 24ae:2003  
Bus 001 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

falcon@falcon-GB-BRi7-H-8550:~/aravis-0.6.4$ arv-tool-0.6
PointGrey-00E77E8F (USB3)

falcon@falcon-GB-BRi7-H-8550:~/aravis-0.6.4/tests$ ./arv-device-test 
Looking for the first available camera
vendor        = Point Grey Research
model         = Chameleon3 CM3-U3-13S2C
device id     = 15171215
sensor width  = 1288
sensor height = 964
image width   = 1280 (max:1288)
image height  = 720 (max:964)
horizontal binning  = 1 (min:1 - max:4)
vertical binning    = 1 (min:1 - max:4)
exposure            = 27161.5 (min:45.5976 - max:27161.5)
exposure auto mode  = Continuous
gain auto mode      = Continuous
trigger selector    = FrameStart
reverse x           = FALSE
payload size  = 921600 (0xe1000)
Frame rate = 36 Hz
Frame rate = 36 Hz
Frame rate = 36 Hz

Please let me know how to get this done.
Thank you

**Comment by EmmanuelP** [comment]
Hi,

If aravis is correctly compiled and installed with the gstreamer plugin in /usr (not /usr/local), you should be able to get the video output from gstreamer using:

```
gst-launch-1.0 aravissrc ! videoconvert ! autovideosink
```

If you have another question related to aravis use, please use the aravis discourse instance instead of github issues:  https://aravis-project.discourse.group/

Cheers.
