### ISSUE TITLE
Commercial licensing option?

### ISSUE THREAD

**Issue by robotwhispering** [AravisProject/aravis#371]
I am reaching out to inquire if there are any possibilities for a commercial closed-source licensing option for Aravis.

**Comment by EmmanuelP** [comment]
Hi,

No there is no commercial closed-source option for using Aravis.

That being said, Aravis is LGPL licensed, which means you are free to link it with a proprietary software. Is really the obilgation to publish your modifications to aravis an issue ?

**Comment by robotwhispering** [comment]
I have no intentions on modifying Aravis. But to close up security holes
that are introduced when you dynamically link libraries.

Warm regards,

Scott Uneberg
(786) 757-7190

**Comment by EmmanuelP** [comment]
> But to close up security holes
that are introduced when you dynamically link libraries.

I don't see why it would prevent the use of LGPL based aravis. Security fixes should definitely be open sourced.

Cheers,

    Emmanuel;
