### ISSUE TITLE
[Question] .cti files

### ISSUE THREAD

**Issue by skaldesh** [AravisProject/aravis#372]
Hi!  
Love your project, works really great. What I am wondering looking at your source code, how does your application find cameras without the `.cti` file of the corresponding vendor? I have a Daheng camera and your viewer can access it.  

As far as I understood the GenICam spec, these `.cti` files are shared libs which are loaded during runtime. So how come your viewer appears to come by without them?

**Comment by EmmanuelP** [comment]
Hi,

> Love your project, works really great.

Thanks.

> how does your application find cameras without the .cti file of the corresponding vendor?

Aravis is vendor independent, and doesn't even use the reference genicam implementation. Transport layers and genicam data parsing are all implemented in aravis source code.

In the future, for such question, please use the aravis discourse instance: https://aravis-project.discourse.group/

Cheers,

    Emmanuel.
