### ISSUE TITLE
Convert ArvStream -> Raw packet data Can do this?

### ISSUE THREAD

**Issue by aksrb1030** [AravisProject/aravis#376]
I'm try to convert ArvStream data to raw packet data because I need to make a binary file using packt. So Can do this? If you do it can you explain how to conver it?

**Platform description:**

- Aravis version V 0.6.3
- OS: Ubuntu 16.04

**Comment by EmmanuelP** [comment]
No, it is not possible and out of the scope of aravis. Why don't you use wireshark if you want to capture the stream packets ?
