### ISSUE TITLE
camera-name field in gst pipeline

### ISSUE THREAD

**Issue by westonCoder** [AravisProject/aravis#409]
This is just a question. 

when ./arv-tool-0.8 is called I get the following printed:
Imperx, Inc-POE-C2010C-RC0000000-00900289 (20.0.0.82)

which part of this do I plug into my gst pipeline as the "camera-name"?

ie. 
gst-launch-1.0 -e --gst-plugin-path=/usr/local/lib aravissrc camera-name="?????" ! fakesink

finally, is the above pipeline correct to test basic plugin functionality?

Thanks,
Weston

**Comment by EmmanuelP** [comment]
Hi Weston,

The name can be either <manufacturer>-<serialnbr>, or <manufacturer>-<model>-<serialnbr>. The documentation about this is lacking.

In your case, you can use `camera-name="Imperx, Inc-POE-C2010C-RC0000000-00900289"`.

In the future, please ask this sort of question on aravis discourse instance: https://aravis-project.discourse.group/

Cheers,

    Emmanuel.
