### ISSUE TITLE
Syntax error parsing genicam file

### ISSUE THREAD

**Issue by zanettea** [AravisProject/aravis#427]
**Describe the bug**
The library reports error parsing genicam files using formulas referencing pVariable names containing dots

**To Reproduce**
See the attached genicam.xml  [file](https://github.com/AravisProject/aravis/files/5421162/genicam.zip)
 (for instance TS.Entry.LineStart pVariable...)

**Expected behavior**

**Camera description:**
 - Manufacturer DALSA
 - Model Linea

**Platform description:**
 - Aravis version 0.8.2

**Comment by EmmanuelP** [comment]
Fixed by #428
