### ISSUE TITLE
Can't detect Basler USB Camera on Nvidia Jetson TX1

### ISSUE THREAD

**Issue by YuryAlkevich** [AravisProject/aravis#43]
I've compiled aravis on Ubuntu 16.04, x86_64 desktop PC and tested it with two cameras:
Basler acA1920-150um (USB camera)  and Basler avA2300-25gm (Ethernet camera). 
Both cameras works well on that machine. But my primary interest is to use aravis on Jetson TX1 (instead of Balser Pylon SDK which currently doesn't support x64 ARM arch). Therefore I've compiled aravis on Jetson TX1 with Ubuntu 16.04, aarch64 ARM, but aravis can't detect USB camera, though Ethernet camera works fine.

**Comment by EmmanuelP** [comment]
Do you see the camera with lsusb ?
Did you connect it to the USB3 port ?
What is the output of 'arv-tool-0.6 -d all:3' ?

**Comment by EmmanuelP** [comment]
It can also be an access right issue. You may want to try using the root account. If it works, check the access right of the /dev/usbmon* files. On fedora, user must be part of the usbmon group.

**Comment by YuryAlkevich** [comment]
Ok, here is what I've got:

[output.txt](https://github.com/AravisProject/aravis/files/750218/output.txt)
[sudo arv-viewer -d all-3.txt](https://github.com/AravisProject/aravis/files/750219/sudo.arv-viewer.-d.all-3.txt)

You were right, with sudo camera can be detected. But as you can see in output.txt, arv-viewer throws error and terminates. I've also attached the second file where I launched arv-viewer in debug mode, and in that case it just hangs on forever.

**Comment by YuryAlkevich** [comment]
Also if I unplug the camera form USB when avr-viewer is hanging in debug mode, I get the following output:
(arv-viewer:19213): GLib-ERROR **: /build/glib2.0-7Ure2w/glib2.0-2.48.2/./glib/gmem.c:130: failed to allocate 8028075781016781059 bytes
Trace/breakpoint trap
And the program terminates

**Comment by EmmanuelP** [comment]
Could be an issue with USB endpoints. What is the output of:

lsusb -v -d 2676:ba02

What version of aravis do you use ?
Could you try the master branch. There is some improvement that could fix an endpoint issue.

**Comment by YuryAlkevich** [comment]
I've pulled latest version of master. The issue still exists. Here is the output of lsusb
[lsusb-output.txt](https://github.com/AravisProject/aravis/files/752127/lsusb-output.txt)
[master-output.txt](https://github.com/AravisProject/aravis/files/752128/master-output.txt)

**Comment by YuryAlkevich** [comment]
up

**Comment by EmmanuelP** [comment]
It is not and endpoint issue.

Without the hardware at hand, it is hard to understand what is wrong. For some reason, aravis doesn't get any answer from the device. You could try to debug the calls to libusb in arv_uv_device_bulk_transfer by printing the error values.

**Comment by mcguire-steve** [comment]
Another option is to enable debugging in LibUSB by exporting LIBUSB_DEBUG=4  and then running something from the suite that tries to access the camera.

**Comment by YuryAlkevich** [comment]
sudo LIBUSB_DEBUG=4 arv-viewer -d all:3
[timestamp] [threadID] facility level [function call] <message>
--------------------------------------------------------------------------------
[ 0.000012] [00001679] libusb: debug [libusb_init] created default context
[ 0.000322] [00001679] libusb: debug [libusb_init] libusb v1.0.20.11004
[ 0.000410] [00001679] libusb: debug [find_usbfs_path] found usbfs at /dev/bus/usb
[ 0.000468] [00001679] libusb: debug [op_init] bulk continuation flag supported
[ 0.000495] [00001679] libusb: debug [op_init] zero length packet flag supported
[ 0.000535] [00001679] libusb: debug [op_init] sysfs can relate devices
[ 0.000561] [00001679] libusb: debug [op_init] sysfs has complete descriptors
[ 0.000887] [00001683] libusb: debug [linux_udev_event_thread_main] udev event thread entering.
[ 0.005954] [00001679] libusb: debug [linux_get_device_address] getting address for device: usb1 detached: 0
[ 0.005992] [00001679] libusb: debug [linux_get_device_address] scan usb1
[ 0.006099] [00001679] libusb: debug [linux_get_device_address] bus=1 dev=1
[ 0.006129] [00001679] libusb: debug [linux_enumerate_device] busnum 1 devaddr 1 session_id 257
[ 0.006151] [00001679] libusb: debug [linux_enumerate_device] allocating new device for 1/1 (session 257)
[ 0.006688] [00001679] libusb: debug [linux_get_device_address] getting address for device: usb2 detached: 0
[ 0.006718] [00001679] libusb: debug [linux_get_device_address] scan usb2
[ 0.006792] [00001679] libusb: debug [linux_get_device_address] bus=2 dev=1
[ 0.006814] [00001679] libusb: debug [linux_enumerate_device] busnum 2 devaddr 1 session_id 513
[ 0.006833] [00001679] libusb: debug [linux_enumerate_device] allocating new device for 2/1 (session 513)
[ 0.007108] [00001679] libusb: debug [linux_get_device_address] getting address for device: 2-1 detached: 0
[ 0.007132] [00001679] libusb: debug [linux_get_device_address] scan 2-1
[ 0.007202] [00001679] libusb: debug [linux_get_device_address] bus=2 dev=2
[ 0.007223] [00001679] libusb: debug [linux_enumerate_device] busnum 2 devaddr 2 session_id 514
[ 0.007241] [00001679] libusb: debug [linux_enumerate_device] allocating new device for 2/2 (session 514)
[ 0.007323] [00001679] libusb: debug [linux_get_parent_info] Dev 0x83f440 (2-1) has parent 0x89f550 (usb2) port 1
[ 0.007561] [00001679] libusb: debug [linux_get_device_address] getting address for device: 2-2 detached: 0
[ 0.007584] [00001679] libusb: debug [linux_get_device_address] scan 2-2
[ 0.007655] [00001679] libusb: debug [linux_get_device_address] bus=2 dev=3
[ 0.007676] [00001679] libusb: debug [linux_enumerate_device] busnum 2 devaddr 3 session_id 515
[ 0.007695] [00001679] libusb: debug [linux_enumerate_device] allocating new device for 2/3 (session 515)
[ 0.007763] [00001679] libusb: debug [linux_get_parent_info] Dev 0x899600 (2-2) has parent 0x89f550 (usb2) port 2
[ 0.008174] [00001679] libusb: debug [linux_get_device_address] getting address for device: usb3 detached: 0
[ 0.008198] [00001679] libusb: debug [linux_get_device_address] scan usb3
[ 0.008269] [00001679] libusb: debug [linux_get_device_address] bus=3 dev=1
[ 0.008290] [00001679] libusb: debug [linux_enumerate_device] busnum 3 devaddr 1 session_id 769
[ 0.008308] [00001679] libusb: debug [linux_enumerate_device] allocating new device for 3/1 (session 769)
[ 0.008560] [00001679] libusb: debug [linux_get_device_address] getting address for device: 3-1 detached: 0
[ 0.008584] [00001679] libusb: debug [linux_get_device_address] scan 3-1
[ 0.008652] [00001679] libusb: debug [linux_get_device_address] bus=3 dev=2
[ 0.008673] [00001679] libusb: debug [linux_enumerate_device] busnum 3 devaddr 2 session_id 770
[ 0.008691] [00001679] libusb: debug [linux_enumerate_device] allocating new device for 3/2 (session 770)
[ 0.008758] [00001679] libusb: debug [linux_get_parent_info] Dev 0x89c960 (3-1) has parent 0x885d30 (usb3) port 1
[ 0.008898] [00001679] libusb: debug [linux_get_device_address] getting address for device: 3-1.1 detached: 0
[ 0.008920] [00001679] libusb: debug [linux_get_device_address] scan 3-1.1
[ 0.008991] [00001679] libusb: debug [linux_get_device_address] bus=3 dev=3
[ 0.009013] [00001679] libusb: debug [linux_enumerate_device] busnum 3 devaddr 3 session_id 771
[ 0.009031] [00001679] libusb: debug [linux_enumerate_device] allocating new device for 3/3 (session 771)
[ 0.009098] [00001679] libusb: debug [linux_get_parent_info] Dev 0x88b1a0 (3-1.1) has parent 0x89c960 (3-1) port 1
[ 0.009429] [00001679] libusb: debug [linux_get_device_address] getting address for device: 3-1.3 detached: 0
[ 0.009452] [00001679] libusb: debug [linux_get_device_address] scan 3-1.3
[ 0.009522] [00001679] libusb: debug [linux_get_device_address] bus=3 dev=4
[ 0.009544] [00001679] libusb: debug [linux_enumerate_device] busnum 3 devaddr 4 session_id 772
[ 0.009562] [00001679] libusb: debug [linux_enumerate_device] allocating new device for 3/4 (session 772)
[ 0.009628] [00001679] libusb: debug [linux_get_parent_info] Dev 0x88b250 (3-1.3) has parent 0x89c960 (3-1) port 3
[ 0.009884] [00001679] libusb: debug [usbi_add_pollfd] add fd 13 events 1
[ 0.009926] [00001679] libusb: debug [usbi_io_init] using timerfd for timeouts
[ 0.009948] [00001679] libusb: debug [usbi_add_pollfd] add fd 15 events 1
[ 0.009979] [00001679] libusb: debug [libusb_get_device_list] 
[ 0.010023] [00001679] libusb: debug [libusb_get_device_descriptor] 
[ 0.010043] [00001679] libusb: debug [libusb_get_device_descriptor] 
[ 0.010060] [00001679] libusb: debug [libusb_get_device_descriptor] 
[ 0.010077] [00001679] libusb: debug [libusb_get_device_descriptor] 
[ 0.010094] [00001679] libusb: debug [libusb_get_device_descriptor] 
[ 0.010115] [00001679] libusb: debug [libusb_get_config_descriptor] index 0
[ 0.010139] [00001679] libusb: debug [parse_configuration] skipping descriptor 0xb
[ 0.010162] [00001679] libusb: debug [parse_endpoint] skipping descriptor 30
[ 0.010181] [00001679] libusb: debug [parse_endpoint] skipping descriptor 30
[ 0.010199] [00001679] libusb: debug [parse_endpoint] skipping descriptor 30
[ 0.010218] [00001679] libusb: debug [parse_endpoint] skipping descriptor 30
[ 0.010245] [00001679] libusb: debug [libusb_open] open 2.3
[ 0.116332] [00001679] libusb: debug [usbi_add_pollfd] add fd 16 events 4
[ 0.116534] [00001679] libusb: debug [libusb_alloc_transfer] transfer 0x89cab8
[ 0.116613] [00001679] libusb: debug [libusb_submit_transfer] transfer 0x89cab8
[ 0.116755] [00001679] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.117751] [00001679] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.118195] [00001679] libusb: debug [handle_events] poll fds modified, reallocating
[ 0.118715] [00001679] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.119156] [00001679] libusb: debug [handle_events] poll() returned 1
[ 0.119582] [00001679] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=4
[ 0.119902] [00001679] libusb: debug [handle_control_completion] handling completion status 0
[ 0.120292] [00001679] libusb: debug [disarm_timerfd] 
[ 0.120676] [00001679] libusb: debug [usbi_handle_transfer_completion] transfer 0x89cab8 has callback 0x7f82836708
[ 0.121044] [00001679] libusb: debug [sync_transfer_cb] actual_length=4
[ 0.121513] [00001679] libusb: debug [libusb_free_transfer] transfer 0x89cab8
[ 0.121990] [00001679] libusb: debug [libusb_alloc_transfer] transfer 0x89cab8
[ 0.122362] [00001679] libusb: debug [libusb_submit_transfer] transfer 0x89cab8
[ 0.122711] [00001679] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.123291] [00001679] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.123915] [00001679] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.124336] [00001679] libusb: debug [handle_events] poll() returned 1
[ 0.124710] [00001679] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=14
[ 0.125079] [00001679] libusb: debug [handle_control_completion] handling completion status 0
[ 0.125433] [00001679] libusb: debug [disarm_timerfd] 
[ 0.127139] [00001679] libusb: debug [usbi_handle_transfer_completion] transfer 0x89cab8 has callback 0x7f82836708
[ 0.127315] [00001679] libusb: debug [sync_transfer_cb] actual_length=14
[ 0.127496] [00001679] libusb: debug [libusb_free_transfer] transfer 0x89cab8
[ 0.127675] [00001679] libusb: debug [libusb_alloc_transfer] transfer 0x89cab8
[ 0.127827] [00001679] libusb: debug [libusb_submit_transfer] transfer 0x89cab8
[ 0.127975] [00001679] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.128248] [00001679] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.128441] [00001679] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.128630] [00001679] libusb: debug [handle_events] poll() returned 1
[ 0.128806] [00001679] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=4
[ 0.128964] [00001679] libusb: debug [handle_control_completion] handling completion status 0
[ 0.129114] [00001679] libusb: debug [disarm_timerfd] 
[ 0.129270] [00001679] libusb: debug [usbi_handle_transfer_completion] transfer 0x89cab8 has callback 0x7f82836708
[ 0.129422] [00001679] libusb: debug [sync_transfer_cb] actual_length=4
[ 0.129582] [00001679] libusb: debug [libusb_free_transfer] transfer 0x89cab8
[ 0.129744] [00001679] libusb: debug [libusb_alloc_transfer] transfer 0x89cab8
[ 0.129895] [00001679] libusb: debug [libusb_submit_transfer] transfer 0x89cab8
[ 0.130043] [00001679] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.130311] [00001679] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.130523] [00001679] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.130707] [00001679] libusb: debug [handle_events] poll() returned 1
[ 0.130884] [00001679] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=28
[ 0.131042] [00001679] libusb: debug [handle_control_completion] handling completion status 0
[ 0.131196] [00001679] libusb: debug [disarm_timerfd] 
[ 0.131352] [00001679] libusb: debug [usbi_handle_transfer_completion] transfer 0x89cab8 has callback 0x7f82836708
[ 0.131506] [00001679] libusb: debug [sync_transfer_cb] actual_length=28
[ 0.131664] [00001679] libusb: debug [libusb_free_transfer] transfer 0x89cab8
[ 0.131829] [00001679] libusb: debug [libusb_alloc_transfer] transfer 0x89cab8
[ 0.131979] [00001679] libusb: debug [libusb_submit_transfer] transfer 0x89cab8
[ 0.132126] [00001679] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.132383] [00001679] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.132573] [00001679] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.132756] [00001679] libusb: debug [handle_events] poll() returned 1
[ 0.132925] [00001679] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=4
[ 0.133076] [00001679] libusb: debug [handle_control_completion] handling completion status 0
[ 0.133227] [00001679] libusb: debug [disarm_timerfd] 
[ 0.133380] [00001679] libusb: debug [usbi_handle_transfer_completion] transfer 0x89cab8 has callback 0x7f82836708
[ 0.133533] [00001679] libusb: debug [sync_transfer_cb] actual_length=4
[ 0.133689] [00001679] libusb: debug [libusb_free_transfer] transfer 0x89cab8
[ 0.133848] [00001679] libusb: debug [libusb_alloc_transfer] transfer 0x89cab8
[ 0.133997] [00001679] libusb: debug [libusb_submit_transfer] transfer 0x89cab8
[ 0.134144] [00001679] libusb: debug [add_to_flying_list] arm timerfd for timeout in 1000ms (first in line)
[ 0.134395] [00001679] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
[ 0.134564] [00001679] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
[ 0.134743] [00001679] libusb: debug [handle_events] poll() returned 1
[ 0.134907] [00001679] libusb: debug [reap_for_handle] urb type=2 status=0 transferred=18
[ 0.135059] [00001679] libusb: debug [handle_control_completion] handling completion status 0
[ 0.135208] [00001679] libusb: debug [disarm_timerfd] 
[ 0.135359] [00001679] libusb: debug [usbi_handle_transfer_completion] transfer 0x89cab8 has callback 0x7f82836708
[ 0.136003] [00001679] libusb: debug [sync_transfer_cb] actual_length=18
[ 0.136128] [00001679] libusb: debug [libusb_free_transfer] transfer 0x89cab8
[ 0.136454] [00001679] libusb: debug [libusb_close] 
[ 0.136593] [00001679] libusb: debug [usbi_remove_pollfd] remove fd 16
[ 0.136750] [00001679] libusb: de...

**Comment by EmmanuelP** [comment]
Thanks, but this log is missing ARAVIS debug output which would help to understand when these libusb calls happen.

I have pushed a patch to master that improves the debug output a bit. Could you give it a try, using `./viewer/arv-viewer -d all:3` ?

By the way, the access right issue can be solved by adding an udev rules file in /etc/udev/rules.d. An example is available in aravis.rules. Just add a line with the right vendor id and put the files in /etc/udev/rules.d/.

**Comment by YuryAlkevich** [comment]
Sorry I haven't shown full debug log. Here is the full log of viewer with last updates from master.
[090217_debug_aravis.txt](https://github.com/AravisProject/aravis/files/762955/090217_debug_aravis.txt)
At 135.903441 I turned off the camera.
Also thank you for the advice about udev rules

**Comment by EmmanuelP** [comment]
For comparison, here is the log of a successful connection:

[successful_connection.txt](https://github.com/AravisProject/aravis/files/770605/successful_connection.txt)

**Comment by Pragneshvirani** [comment]
Hi,
You found a solution, Even I am facing the same problem.Is it because of insufficient power for the camera? Because camera Power LED goes off after 1-2  second of connection.

Thanks.

**Comment by YuryAlkevich** [comment]
Hello,
We are using Basler cameras and software developers of Basler have released new SDK for arm x64 arch recently. So now we don't need aravis libraries and we still haven't found the solution for the issue.

**Comment by Pragneshvirani** [comment]
Thanks for the update. 
Even we are trying to interface Basler camera. From their(Basler) web I do not see arm x64 SDK.Can see only 32bit Arch.Can you please point out from where can get this?
Thank You!

**Comment by EmmanuelP** [comment]
For the record, a user reported a successful use of aravis 0.5.7 with 4 Basler USB cameras, from a jetson TX1 board using ubuntu. Here is the camera list:

![image](https://cloud.githubusercontent.com/assets/136864/25782658/70adf6f2-334f-11e7-8890-2cc68d4e4587.png)

Thanks to him and his company, I will soon receive a TX2 board and be able to test aravis using this platform.

@Pragneshvirani If using a proprietary library is not an issue for you, you may also want to try Pleora's eBus software. I don't know if they propose 64 bit ARM support though.

**Comment by Pragneshvirani** [comment]
Thanks, @EmmanuelP for the update. If Basler has x64 support then defiantly we look for, because later we need to have a camera I/O control also for LED strobe.which don't I think we can get from Aravis or Pleora? 

@YuryAlkevich Did you already tried with Basler x64 SDK? 

Thanks.

Regards,
Pragnesh

**Comment by EmmanuelP** [comment]
> because later we need to have a camera I/O control also for LED strobe.which don't I think we can get from Aravis or Pleora?

If these features are exposed through Genicam, and I guess they are, they should be supported by aravis and pleora.

**Comment by Pragneshvirani** [comment]
@EmmanuelP Noted, I will try that. Thanks a lot.

**Comment by YuryAlkevich** [comment]
@Pragneshvirani
I asked a support team to send me a beta version of the SDK. Official release will be in June. 
Here is the link to beta, which they send me
https://1drv.ms/u/s!Ag-yO1E4-6Eahp4Qf0i6zFOUJyjcmQ

**Comment by Pragneshvirani** [comment]
Just to update, I tried Basler x64 SDK and it's working fine.
Thank you so much @YuryAlkevich & @EmmanuelP

**Comment by EmmanuelP** [comment]
Since I have a report of working devices on Jetson TX1 platform, and the discussion is now about Basler SDK, I'm closing this issue.
