### ISSUE TITLE
handle to ArvInterface

### ISSUE THREAD

**Issue by RalfB78** [AravisProject/aravis#47]
I've used several versions (0.3.x, 0.4.x, 0.5.x) of aravis to control GigEVision cameras in the past.
Since I needed some low-level control, I've used functions like  arv_interface_update_device_list(), arv_interface_get_device_address(), arv_interface_get_device_physical_id().
All of these need a ArvInterface pointer as a parameter, that I got by calling 
arv_gv_interface_get_instance().
In the current release (0.5.7) this function was removed.
I can't see how to get a valid ArvInterface* anymore.
Do I have missed something?

Thanks

**Comment by EmmanuelP** [comment]
In the development release of Aravis, I have made part of the API private. You should be able to achieve what you did with the functions defined in arvsystem.h. It was missing get_device_physical_id, by it is now in master.
