### ISSUE TITLE
Connect Basler USB Cam to third-party tools

### ISSUE THREAD

**Issue by srediske** [AravisProject/aravis#484]
Hey!

Can i use aravis to use a Basler USB camera (e.g. acA1440-220uc) in tools like Microsoft Teams or [BoofCV](https://boofcv.org/index.php?title=Main_Page) in Ubuntu 20.04?

**Comment by EmmanuelP** [comment]
Hi,

Not out of the box, and it is not really the typical use case for industrial cameras. But with a combination of aravis / v4l2 loopback and gstreamer, it should be possible.

In the futur, please ask this sort of question on aravis discourse instance. The issue tracker in github is not the right tool.

Have fun using aravis !

Cheers.
