### ISSUE TITLE
Can't detect a2A2590-60umBAS via USB3 on Ubuntu 20.04

### ISSUE THREAD

**Issue by antortjim** [AravisProject/aravis#507]
**Describe the bug**
My a2A2590-60umBAS USB3 camera from Basler is not getting recognized by aravis, even though it works as expected when using Pylon Viewer.

**To Reproduce**
From the build folder created during install (see *How I installed aravis*):

```
LD_LIBRARY_PATH=./src/:$LIBRARY_PATH /usr/local/bin/arv-camera-test-0.8
# Looking for the first available camera
# No camera found: No supported device found
```

**Expected behavior**
I expected the camera a2A2590-60umBAS to be listed in the output

**Camera description:**
 - Basler
 - a2A2590-60umBAS
 - USB3
 - Powered via the USB3 cable (no dedicated PSU)
 
**Platform description:**
```
aravis 0.8.9
aravis git hash: af27d0c3cb32d5f9cb4f78d61ef03a496229765b
Ubuntu 20.04
Python 3.7.4
conda 4.10.1
gcc 9.3.0
g++ 9.3.0
GNU Make 4.2.1 
meson 0.58.0
ninja 1.10.0.git.kitware.jobserver-1
```

```
uname -a
# Linux gbw-d-l0120 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**How I installed aravis**

```
git clone https://github.com/AravisProject/aravis/
pip install meson
pip install ninja
apt install libglib2.0-dev
apt install libxml2-dev
```
```
cd aravis
meson build
cd build
ninja
ninja install
```

**Additional context**

I also tried passing the name of the camera by adding --name a2A2590-60umBAS but I get this
```
LD_LIBRARY_PATH=./src/:$LIBRARY_PATH /usr/local/bin/arv-camera-test-0.8 --name a2A2590-60umBAS
# Looking for camera 'a2A2590-60umBAS'
# No camera found: Device 'a2A2590-60umBAS' not found
```

Running in debug mode
```
LD_LIBRARY_PATH=./src/:$LIBRARY_PATH /usr/local/bin/arv-camera-test-0.8 --debug all:3
# [18:56:31.052] 🅸 interface> [GvDiscoverSocket::new] Add interface 127.0.0.1
# [18:56:31.053] 🅸 interface> [GvDiscoverSocket::new] Add interface 10.34.178.0
# No device found
```
This does not change if I run either of the commands as root

The camera is listed in the output of lsusb -t as a Miscellaneous Device

```
lsusb -t

/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    |__ Port 2: Dev 4, If 0, Class=Miscellaneous Device, Driver=, 5000M
    |__ Port 2: Dev 4, If 1, Class=Miscellaneous Device, Driver=, 5000M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 480M
    |__ Port 1: Dev 2, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
    |__ Port 3: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/8p, 480M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=ehci-pci/2p, 480M
    |__ Port 1: Dev 7, If 0, Class=Hub, Driver=hub/6p, 480M
```

PS I don't know how to link the libaravis-0.8.so.0 file available in src, but the LD_LIBRARY_PATH trick does the job (not ideal, I know).

EDIT:

I have installed the `libusb-1.0-0-dev` package and rebooted the system, with no effect on the tests shown above.

Could you please let me know how to fix this issue? Thank you very much!
Antonio

**Comment by EmmanuelP** [comment]
You must reconfigure the meson build.

`meson --reconfigure` in the build directory should do the trick.

**Comment by antortjim** [comment]
I ran in the build folder

````
meson --reconfigure
ninja
sudo ninja install
````

and the camera is now detected!! But now I get the error

```
Failed to read the current device configuration: node 'DeviceVendorName' not found
```

Running with debug option generates a pretty long log, which I am attaching here
[log.txt](https://github.com/AravisProject/aravis/files/6454771/log.txt)

I must say I am now running this via ssh, maybe running this on the standard gnome session might be the trick.

Thanks again,
Antonio

**Comment by EmmanuelP** [comment]
Please attach the output of `arv-tool-0.8 genicam`.

**Comment by antortjim** [comment]
[arg_tool_genicam.txt](https://github.com/AravisProject/aravis/files/6454909/arg_tool_genicam.txt)

**Comment by EmmanuelP** [comment]
Please attach the output of `arv-tool-0.8 features` and `arv-tool-0.8 values`.

**Comment by antortjim** [comment]
```
LD_LIBRARY_PATH=./src/:$LIBRARY_PATH /usr/local/bin/arv-tool-0.8 features > features.txt
LD_LIBRARY_PATH=./src/:$LIBRARY_PATH /usr/local/bin/arv-tool-0.8 values > values.txt
```

[features.txt](https://github.com/AravisProject/aravis/files/6457302/features.txt)
[values.txt](https://github.com/AravisProject/aravis/files/6457303/values.txt)

**Comment by EmmanuelP** [comment]
The Genicam data makes use of String nodes, which are not implemented in Aravis yet.

**Comment by antortjim** [comment]
No problem!
I see, that's ok, at least we know what it is! Hope it's not too difficult for the devteam to implement this (if they decide to)! In any case, thank you for your quick support :) I will just continue to use pypylon for now instead https://github.com/basler/pypylon

**Comment by EmmanuelP** [comment]
Please try #508

**Comment by EmmanuelP** [comment]
> So it seems to fix the problem!! 

Thanks for the testing. I'm closing this issue.

> installed under /usr/local/bin, i.e. I am missing arv-viewer-0.8, which is the actual GUI, right? Is it possible I still did something wrong?

It is the same issue as for USB support, you have to install the needed development packages. In the output of the initial meson build configuration, there is probably some messages indicating what you are missing (gtk3, gstreamer, libnotify...).
