### ISSUE TITLE
Basler daA1280-54uc support

### ISSUE THREAD

**Issue by GauthierPerrod** [AravisProject/aravis#517]
**Describe the bug**
Two bugs encountered when using aravis on a Basler usb3vison

``` Incomplete image received, dropping (received 1310868 / expected 3686400) ```

I fixed using this https://github.com/AravisProject/aravis/issues/314
(the 256*256 things)

Second issue was that gstaravissrc wasn't working:

``` GstPipeline:pipeline0/GstAravis:aravis0: Could not set caps on camera "Basler-23484193": node 'AcquisitionFrameRateEnable' not found ``` 

I fixed it by removing the followings lines :
```
+                        if (local_error == NULL)                                                                                           
+                             arv_camera_set_boolean (camera, "AcquisitionFrameRateEnable", TRUE, &local_error); 
 ```
(l990-991)
in /src/arvcamera.c

**To Reproduce**
- Using a daA1280-54uc Basler on a jetson tx2  / jetson nx

**Expected behavior**
Unable to use arv-viewer and gstaravissrc

**Camera description:**
 - Basler
 - daA1280-54uc
 - usb3vison

**Platform description:**
 - Aravis version 0.8
 - OS: Ubuntu 18.04
 - Jetson nx / tx2

**Additional context**
My solution is working but it does'nt seem to be very reliable

**Comment by EmmanuelP** [comment]
Could you attach the output of `arv-tool-0.8 genicam` ?

**Comment by EmmanuelP** [comment]
Frame rate setting should have improved in the latest release. Please test Aravis 0.8.17, and reopen this issue if it is not fixed.

**Comment by akshayash001** [comment]
can anyone know that Basler daA1280-54uc support xilinx drivers ,linux drivers or any bare metal drivers?
