### ISSUE TITLE
localtime_r needs -D_POSIX_C_SOURCE in mingw64

### ISSUE THREAD

**Issue by eudoxos** [AravisProject/aravis#525]
[localtime_r manpage](https://linux.die.net/man/3/localtime_r) explains the feature macros. Otherwise `localtime_r` is not defined mingw64 (see also e.g. https://github.com/m-ab-s/media-autobuild_suite/issues/1211). This can be fixed by adding `-D_POSIX_C_SOURCE` to `library_c_args` in `src/meson.build` though I am not sure whether this can be done unconditionally.

https://github.com/AravisProject/aravis/blob/76254b7faf59901166ec78a73e94b03a0cd8bb77/src/arvdebug.c#L156

**Comment by EmmanuelP** [comment]
Hi @eudoxos 

Does #526 fix your issue ?

**Comment by eudoxos** [comment]
Perfect, please merge that!

**Comment by EmmanuelP** [comment]
Unfortunately, it looks like localtime is not threadsafe. I have to find another solution.

**Comment by EmmanuelP** [comment]
#526 is updated and use glib API now.
