### ISSUE TITLE
Free buffers

### ISSUE THREAD

**Issue by drmcnelson** [AravisProject/aravis#559]
A typical use of the library seems to be allocate some buffers, push them on to the stream and start acquisition.   The call to try_pop_buffer() then returns a filled buffer when available.

What seems to be needed is a way to free the buffers that were pushed.

In particular I am interested in having a call for this available in the python interface.

Thank you

**Comment by EmmanuelP** [comment]
Hi,

There is normally no need to free buffers. You just have to push them back to the stream thread. They will be freed upon ArvStream destruction.

For future questions about Aravis use, please post them on Aravis discourse instance: https://aravis-project.discourse.group/

Cheers.

**Comment by drmcnelson** [comment]
Hi

What happens if the payload size changes?

It seems from code examples that the buffer size is matched to the payload,
and the payload matches the size of the ROI.

And the ROI could be smaller or larger from one moment to the next

**Comment by EmmanuelP** [comment]
Le lun., août 23 2021 at 04:44:34 -0700, drmcnelson 
***@***.***> a écrit :
> What happens if the payload size changes?
> 

Aravis does not support a change in the payload size during an 
acquisition sequence.

	Emmanuel.

**Comment by drmcnelson** [comment]
What about different acquisition sequences?

Meaning, finish one acq, change the ROI and start another.

**Comment by EmmanuelP** [comment]
Le lun., août 23 2021 at 04:58:57 -0700, drmcnelson 
***@***.***> a écrit :
> What about different acquisition sequences?
> 
>  Meaning, finish one acq, change the ROI and start another.

Please have a look at `tests/arvroitest.c`.

	Emmanue.

**Comment by drmcnelson** [comment]
Very good, thank you.  Is there a python equivalent?

It looks like del(stream) might do it.   Is that how you intended it should
be done?

**Comment by EmmanuelP** [comment]
Le lun., août 23 2021 at 05:08:59 -0700, drmcnelson 
***@***.***> a écrit :
> Very good, thank you. Is there a python equivalent?
> 

No, sorry.

>  It looks like del(stream) might do it. Is that how you intended it 
> should
>  be done?

arv_stream_stop_thread (..., TRUE) will delete all the buffers it has 
reference to.

	Emmanuel.

**Comment by drmcnelson** [comment]
Thank you, I will try that.

And thank you for making Aravis available,  It enables the next step in my
research.
