### ISSUE TITLE
Install on Mac using macports

### ISSUE THREAD

**Issue by lawny13** [AravisProject/aravis#56]
Hi, 

I would like to install and run Aravis on my mac (since there is no pymba/vimba option). 

Though I saw there is a homebrew method, I was wondering if there is a method to do the same but using macports. Since macports is my current python package manager I would like to stick with it, and brew + ports simply do not live well together on a mac.

Any help would be appreciated.

**Comment by EmmanuelP** [comment]
Please ask on the aravis mailing list:

http://www.freelists.org/list/aravis
