### ISSUE TITLE
How to get FrameNumber and FrameLoss in python?

### ISSUE THREAD

**Issue by tahasadr** [AravisProject/aravis#580]
Hi there
I'm trying to use python interface to setup realtime hardware triggered image capturing via callbacks.
my question is how can i get framenumber and how can i get notified when there is frame loss?

**Comment by EmmanuelP** [comment]
HI @tahasadr 

This is not an issue. Please ask on aravis discourse instance: https://aravis-project.discourse.group/

Thanks.
