### ISSUE TITLE
Cannot set caps on Mono10 camera

### ISSUE THREAD

**Issue by jamietansm** [AravisProject/aravis#606]
Hello,

I want to create a gstreamer pipeline that takes data from a Mono10 USB3.0 camera and writes it to a video device. Based on my understanding, Mono10 data should be stored using GRAY16_LE, like so:

gst-launch-1.0 aravissrc ! video/x-raw,format=GRAY16_LE,width=1280,height=1024 ! videoconvert ! video/x-raw,format=GRAY16_LE ! v4l2sink device=/dev/video0

This pipeline works well on Virtual Machine, but not on a NVIDIA jetson board. I get the error below:

ERROR: from element /GstPipeline:pipeline0/GstAravis:aravis0: Could not set caps on camera “”: Value not found in ‘PixelFormat’
Additional debug info:
…/gst/gstaravis.c(373): gst_aravis_set_caps (): /GstPipeline:pipeline0/GstAravis:aravis0
Execution ended after 0:00:00.041121658
Setting pipeline to PAUSED …
Setting pipeline to READY …
Setting pipeline to NULL …
Freeing pipeline …

I have checked that arv-tool-0.8 Control PixelFormat=Mono10. I am using the following configurations on both the VM and jetson:
GStreamer version 1.14.5
Ubuntu 18.04 LTS (64-bit)
Aravis 0.8.19

Would appreciate your help on this, thank you!

**Comment by EmmanuelP** [comment]
Answered here: https://aravis-project.discourse.group/t/cannot-set-caps-on-mono10-camera/341

Which is the right location for this sort of questions.

Cheers.
