### ISSUE TITLE
Cross compilation for ARMv7

### ISSUE THREAD

**Issue by sankycui** [AravisProject/aravis#607]
Hi,
When I cross compile the latest master v0.8 on WSL2 Ubuntu20.04, I use arm-linux-gnueabihf- to cross compile for ARMv7 on x64, I found need some ARM dependency libraries like: "glib-2.0,  gobject-2.0, gio-2.0, libxml-2.0, zlib, libusb-1.0", so, where I can get these libraries for ARM7 cross-compile? Should I cross compile them by myself？Thank you!

**environment:**
name@name:/mnt/d/code/vision/aravis-master_arm/build$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
name@name:/mnt/d/code/vision/aravis-master_arm/build$ uname -a
Linux name 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**meson cross compilation configuration:**
[binaries]
c = '/usr/bin/arm-linux-gnueabihf-gcc'
cpp = '/usr/bin/arm-linux-gnueabihf-g++'
ar = '/usr/bin/arm-linux-gnueabihf-ar'
strip = '/usr/bin/arm-linux-gnueabihf-strip'
pkgconfig = '/usr/bin/pkg-config'
cmake='/usr/bin/cmake'
#exe_wrapper = 'qemu' # A command used to run generated executables.

[properties]
#sys_root='/opt/ti-processor-sdk-linux-am57xx-evm-06.00.00.07/linux-devkit/sysroots/armv7at2hf-neon-linux-gnueabi/'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7hl'
endian = 'big'

**Compilation logs:**
name@name:/mnt/d/code/vision/aravis-master_arm/build$ ninja
[1/150] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvenums.c.o'.
FAILED: src/25a6634@@aravis-0.8@sha/arvenums.c.o
/usr/bin/arm-linux-gnueabihf-gcc -Isrc/25a6634@@aravis-0.8@sha -Isrc -I../src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libxml2 -I/usr/include/libusb-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wstrict-prototypes -Wunused -Wunused-variable -Wdeclaration-after-statement -Wformat=2 -Wimplicit-function-declaration -Winit-self -Wmissing-include-dirs -Wmissing-prototypes -Wpointer-arith -Wformat-nonliteral -Wmaybe-uninitialized -fvisibility=hidden -fPIC -pthread -DARAVIS_COMPILATION -MD -MQ 'src/25a6634@@aravis-0.8@sha/arvenums.c.o' -MF 'src/25a6634@@aravis-0.8@sha/arvenums.c.o.d' -o 'src/25a6634@@aravis-0.8@sha/arvenums.c.o' -c ../src/arvenums.c
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from ../src/arvenums.h:31,
                 from ../src/arvenums.c:23:
/usr/include/glib-2.0/glib/gtypes.h: In function ‘_GLIB_CHECKED_ADD_U64’:
/usr/include/glib-2.0/glib/gmacros.h:738:31: error: static assertion failed: "Expression evaluates to false"
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                               ^~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:463:3: note: in expansion of macro ‘G_STATIC_ASSERT’
  463 |   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
      |   ^~~~~~~~~~~~~~~
[2/150] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvdebug.c.o'.
FAILED: src/25a6634@@aravis-0.8@sha/arvdebug.c.o
/usr/bin/arm-linux-gnueabihf-gcc -Isrc/25a6634@@aravis-0.8@sha -Isrc -I../src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libxml2 -I/usr/include/libusb-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wstrict-prototypes -Wunused -Wunused-variable -Wdeclaration-after-statement -Wformat=2 -Wimplicit-function-declaration -Winit-self -Wmissing-include-dirs -Wmissing-prototypes -Wpointer-arith -Wformat-nonliteral -Wmaybe-uninitialized -fvisibility=hidden -fPIC -pthread -DARAVIS_COMPILATION -MD -MQ 'src/25a6634@@aravis-0.8@sha/arvdebug.c.o' -MF 'src/25a6634@@aravis-0.8@sha/arvdebug.c.o.d' -o 'src/25a6634@@aravis-0.8@sha/arvdebug.c.o' -c ../src/arvdebug.c
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/glib/gprintf.h:21,
                 from ../src/arvdebug.c:28:
/usr/include/glib-2.0/glib/gtypes.h: In function ‘_GLIB_CHECKED_ADD_U64’:
/usr/include/glib-2.0/glib/gmacros.h:738:31: error: static assertion failed: "Expression evaluates to false"
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                               ^~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:463:3: note: in expansion of macro ‘G_STATIC_ASSERT’
  463 |   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
      |   ^~~~~~~~~~~~~~~
[3/150] Compiling C object 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvresources.c.o'.
FAILED: src/25a6634@@aravis-0.8@sha/meson-generated_.._arvresources.c.o
/usr/bin/arm-linux-gnueabihf-gcc -Isrc/25a6634@@aravis-0.8@sha -Isrc -I../src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libxml2 -I/usr/include/libusb-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wstrict-prototypes -Wunused -Wunused-variable -Wdeclaration-after-statement -Wformat=2 -Wimplicit-function-declaration -Winit-self -Wmissing-include-dirs -Wmissing-prototypes -Wpointer-arith -Wformat-nonliteral -Wmaybe-uninitialized -fvisibility=hidden -fPIC -pthread -DARAVIS_COMPILATION -MD -MQ 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvresources.c.o' -MF 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvresources.c.o.d' -o 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvresources.c.o' -c src/arvresources.c
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from /usr/include/glib-2.0/gio/gioenums.h:28,
                 from /usr/include/glib-2.0/gio/giotypes.h:28,
                 from /usr/include/glib-2.0/gio/gio.h:26,
                 from src/arvresources.c:1:
/usr/include/glib-2.0/glib/gtypes.h: In function ‘_GLIB_CHECKED_ADD_U64’:
/usr/include/glib-2.0/glib/gmacros.h:738:31: error: static assertion failed: "Expression evaluates to false"
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                               ^~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:463:3: note: in expansion of macro ‘G_STATIC_ASSERT’
  463 |   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
      |   ^~~~~~~~~~~~~~~
[4/150] Compiling C object 'src/25a6634@@aravis-0.8@sha/arvsystem.c.o'.
FAILED: src/25a6634@@aravis-0.8@sha/arvsystem.c.o
/usr/bin/arm-linux-gnueabihf-gcc -Isrc/25a6634@@aravis-0.8@sha -Isrc -I../src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libxml2 -I/usr/include/libusb-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wstrict-prototypes -Wunused -Wunused-variable -Wdeclaration-after-statement -Wformat=2 -Wimplicit-function-declaration -Winit-self -Wmissing-include-dirs -Wmissing-prototypes -Wpointer-arith -Wformat-nonliteral -Wmaybe-uninitialized -fvisibility=hidden -fPIC -pthread -DARAVIS_COMPILATION -MD -MQ 'src/25a6634@@aravis-0.8@sha/arvsystem.c.o' -MF 'src/25a6634@@aravis-0.8@sha/arvsystem.c.o.d' -o 'src/25a6634@@aravis-0.8@sha/arvsystem.c.o' -c ../src/arvsystem.c
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from ../src/arvenums.h:31,
                 from ../src/arvtypes.h:30,
                 from ../src/arvsystem.h:31,
                 from ../src/arvsystem.c:23:
/usr/include/glib-2.0/glib/gtypes.h: In function ‘_GLIB_CHECKED_ADD_U64’:
/usr/include/glib-2.0/glib/gmacros.h:738:31: error: static assertion failed: "Expression evaluates to false"
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                               ^~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:463:3: note: in expansion of macro ‘G_STATIC_ASSERT’
  463 |   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
      |   ^~~~~~~~~~~~~~~
[5/150] Compiling C object 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypesprivate.c.o'.
FAILED: src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypesprivate.c.o
/usr/bin/arm-linux-gnueabihf-gcc -Isrc/25a6634@@aravis-0.8@sha -Isrc -I../src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libxml2 -I/usr/include/libusb-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wstrict-prototypes -Wunused -Wunused-variable -Wdeclaration-after-statement -Wformat=2 -Wimplicit-function-declaration -Winit-self -Wmissing-include-dirs -Wmissing-prototypes -Wpointer-arith -Wformat-nonliteral -Wmaybe-uninitialized -fvisibility=hidden -fPIC -pthread -DARAVIS_COMPILATION -MD -MQ 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypesprivate.c.o' -MF 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypesprivate.c.o.d' -o 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypesprivate.c.o' -c src/arvenumtypesprivate.c
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from src/arvenumtypesprivate.h:6,
                 from src/arvenumtypesprivate.c:4:
/usr/include/glib-2.0/glib/gtypes.h: In function ‘_GLIB_CHECKED_ADD_U64’:
/usr/include/glib-2.0/glib/gmacros.h:738:31: error: static assertion failed: "Expression evaluates to false"
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                               ^~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:463:3: note: in expansion of macro ‘G_STATIC_ASSERT’
  463 |   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
      |   ^~~~~~~~~~~~~~~
In file included from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from src/arvenumtypesprivate.h:6,
                 from src/arvenumtypesprivate.c:4:
../src/arvgvspprivate.h: In function ‘arv_gvsp_packet_get_frame_id’:
/usr/include/glib-2.0/glib/gtypes.h:203:53: warning: left shift count >= width of type [-Wshift-count-overflow]
  203 |  (guint64) G_GINT64_CONSTANT (0x00000000000000ffU)) << 56) | \
      |                                                     ^~
/usr/include/glib-2.0/glib/gtypes.h:370:36: note: in expansion of macro ‘GUINT64_SWAP_LE_BE_CONSTANT’
  370 | #  define GUINT64_SWAP_LE_BE(val) (GUINT64_SWAP_LE_BE_CONSTANT (val))
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:173:29: note: in expansion of macro ‘GUINT64_SWAP_LE_BE’
  173 | #define GUINT64_TO_BE(val) (GUINT64_SWAP_LE_BE (val))
      |                             ^~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:397:31: note: in expansion of macro ‘GUINT64_TO_BE’
  397 | #define GUINT64_FROM_BE(val) (GUINT64_TO_BE (val))
      |                               ^~~~~~~~~~~~~
../src/arvgvspprivate.h:244:10: note: in expansion of macro ‘GUINT64_FROM_BE’
  244 |   return GUINT64_FROM_BE(header->frame_id);
      |          ^~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:205:53: warning: left shift count >= width of type [-Wshift-count-overflow]
  205 |  (guint64) G_GINT64_CONSTANT (0x000000000000ff00U)) << 40) | \
      |                                                     ^~
/usr/include/glib-2.0/glib/gtypes.h:370:36: note: in expansion of macro ‘GUINT64_SWAP_LE_BE_CONSTANT’
  370 | #  define GUINT64_SWAP_LE_BE(val) (GUINT64_SWAP_LE_BE_CONSTANT (val))
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:173:29: note: in expansion of macro ‘GUINT64_SWAP_LE_BE’
  173 | #define GUINT64_TO_BE(val) (GUINT64_SWAP_LE_BE (val))
      |                             ^~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:397:31: note: in expansion of macro ‘GUINT64_TO_BE’
  397 | #define GUINT64_FROM_BE(val) (GUINT64_TO_BE (val))
      |                               ^~~~~~~~~~~~~
../src/arvgvspprivate.h:244:10: note: in expansion of macro ‘GUINT64_FROM_BE’
  244 |   return GUINT64_FROM_BE(header->frame_id);
      |          ^~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:215:53: warning: right shift count >= width of type [-Wshift-count-overflow]
  215 |  (guint64) G_GINT64_CONSTANT (0x00ff000000000000U)) >> 40) | \
      |                                                     ^~
/usr/include/glib-2.0/glib/gtypes.h:370:36: note: in expansion of macro ‘GUINT64_SWAP_LE_BE_CONSTANT’
  370 | #  define GUINT64_SWAP_LE_BE(val) (GUINT64_SWAP_LE_BE_CONSTANT (val))
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:173:29: note: in expansion of macro ‘GUINT64_SWAP_LE_BE’
  173 | #define GUINT64_TO_BE(val) (GUINT64_SWAP_LE_BE (val))
      |                             ^~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:397:31: note: in expansion of macro ‘GUINT64_TO_BE’
  397 | #define GUINT64_FROM_BE(val) (GUINT64_TO_BE (val))
      |                               ^~~~~~~~~~~~~
../src/arvgvspprivate.h:244:10: note: in expansion of macro ‘GUINT64_FROM_BE’
  244 |   return GUINT64_FROM_BE(header->frame_id);
      |          ^~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:217:53: warning: right shift count >= width of type [-Wshift-count-overflow]
  217 |  (guint64) G_GINT64_CONSTANT (0xff00000000000000U)) >> 56)))
      |                                                     ^~
/usr/include/glib-2.0/glib/gtypes.h:370:36: note: in expansion of macro ‘GUINT64_SWAP_LE_BE_CONSTANT’
  370 | #  define GUINT64_SWAP_LE_BE(val) (GUINT64_SWAP_LE_BE_CONSTANT (val))
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:173:29: note: in expansion of macro ‘GUINT64_SWAP_LE_BE’
  173 | #define GUINT64_TO_BE(val) (GUINT64_SWAP_LE_BE (val))
      |                             ^~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:397:31: note: in expansion of macro ‘GUINT64_TO_BE’
  397 | #define GUINT64_FROM_BE(val) (GUINT64_TO_BE (val))
      |                               ^~~~~~~~~~~~~
../src/arvgvspprivate.h:244:10: note: in expansion of macro ‘GUINT64_FROM_BE’
  244 |   return GUINT64_FROM_BE(header->frame_id);
      |          ^~~~~~~~~~~~~~~
In file included from ../src/arvbufferprivate.h:27,
                 from src/arvenumtypesprivate.c:5:
../src/arvgvspprivate.h: In function ‘arv_gvsp_packet_get_timestamp’:
../src/arvgvspprivate.h:360:59: warning: left shift count >= width of type [-Wshift-count-overflow]
  360 |  timestamp = ( (guint64) g_ntohl (leader->timestamp_high) << 32) | g_ntohl (leader->timestamp_low);
      |                                                           ^~
[6/150] Compiling C object 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypes.c.o'.
FAILED: src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypes.c.o
/usr/bin/arm-linux-gnueabihf-gcc -Isrc/25a6634@@aravis-0.8@sha -Isrc -I../src -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/libxml2 -I/usr/include/libusb-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -Wduplicated-branches -Wimplicit-fallthrough -Wmisleading-indentation -Wstrict-prototypes -Wunused -Wunused-variable -Wdeclaration-after-statement -Wformat=2 -Wimplicit-function-declaration -Winit-self -Wmissing-include-dirs -Wmissing-prototypes -Wpointer-arith -Wformat-nonliteral -Wmaybe-uninitialized -fvisibility=hidden -fPIC -pthread -DARAVIS_COMPILATION -MD -MQ 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypes.c.o' -MF 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypes.c.o.d' -o 'src/25a6634@@aravis-0.8@sha/meson-generated_.._arvenumtypes.c.o' -c src/arvenumtypes.c
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/glib-2.0/gobject/gbinding.h:28,
                 from /usr/include/glib-2.0/glib-object.h:22,
                 from src/arvenumtypes.h:6,
                 from src/arvenumtypes.c:4:
/usr/include/glib-2.0/glib/gtypes.h: In function ‘_GLIB_CHECKED_ADD_U64’:
/usr/include/glib-2.0/glib/gmacros.h:738:31: error: static assertion failed: "Expression evaluates to false"
  738 | #define G_STATIC_ASSERT(expr) _Static_assert (expr, "Expression evaluates to false")
      |                               ^~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtypes.h:463:3: note: in expansion of macro ‘G_STATIC_ASSERT’
  463 |   G_STATIC_ASSERT(sizeof (unsigned long long) == sizeof (guint64));
      |   ^~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by EmmanuelP** [comment]
Hi,

> When I cross compile the latest master v0.8 on WSL2 Ubuntu20.04, I use arm-linux-gnueabihf- to cross compile for ARMv7 on x64, I found need some ARM dependency libraries like: "glib-2.0, gobject-2.0, gio-2.0, libxml-2.0, zlib, libusb-1.0", so, where I can get these libraries for ARM7 cross-compile? Should I cross compile them by myself？Thank you!

I guess you will find the relevant informations following this link https://wiki.debian.org/Multiarch/HOWTO

Cross compilation setup is out of scope of this issue tracker, unless you have issues during the cross compilation itself.

I'm closing this issue then.

Cheers.
