### ISSUE TITLE
arv_gc_feature_node_get_actual_access_mode returns unexpected ARV_GC_ACCESS_MODE_RO

### ISSUE THREAD

**Issue by TIS-Edgar** [AravisProject/aravis#634]
Hi Emmanuel,

**Describe the bug**

`arv_gc_feature_node_get_actual_access_mode` returns `ARV_GC_ACCESS_MODE_RO`
for free-floating Integer nodes, whereas `ARV_GC_ACCESS_MODE_RW` is expected.

**To Reproduce**

A small c program that reproduces the problem can be found here,
as well as the corresponding genicam description:
https://gist.github.com/TIS-Edgar/c2e4bcc36ff581bc29cce35c8762e81f

**Expected behavior**

The node should have RW access mode.

**Camera description:**

Seems to be reproducible with all TIS cameras. GigE and USB3.
Verified with DMK 33UX273, DFK 33GP1300 and DFK 33GP1300.

**Platform description:**
 - current master (08dc0ba0)
 - OS: Debian Testing
 - Hardware: amd64

This seems to be fixable by having [arvgcfeaturenode.c@522:_get_access_mode](https://github.com/AravisProject/aravis/blob/main/src/arvgcfeaturenode.c#L568) return `ARV_GC_ACCESS_MODE_RW`.

As always, thank you in advance!

**Comment by EmmanuelP** [comment]
Please try #635
