### ISSUE TITLE
Missing dependencies with meson build

### ISSUE THREAD

**Issue by Embeddediot** [AravisProject/aravis#646]
Hello i am in the process of installling the aravis libary on a jetson nano in order to work with a jai camera. I have fulfilled most dependencies but still get two errors that i am not able to remove. "Compiler for C supports arguments -Wenum-conversion: NO" and "Run-time dependency gi-docgen found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency gi-docgen"
Anyone here who have experienced the same problem?
I have attached the terminal output when building.
Your help is very appreciated!
Best regards.

[terminal-output.txt](https://github.com/AravisProject/aravis/files/8340480/terminal-output.txt)

**Comment by EmmanuelP** [comment]
Hi,

I don't see any error in your terminal output.

Anyway, please start a discussion on the aravis discourse instance:

https://aravis-project.discourse.group/c/using-aravis/8

Thanks.
