### ISSUE TITLE
Install via package manager (apt?)

### ISSUE THREAD

**Issue by turowicz** [AravisProject/aravis#649]
Would be really good to be able to just install the app via package manager or download the AppImage binary.

**Comment by EmmanuelP** [comment]
Aravis is available on [debian](https://packages.debian.org/source/sid/aravis) and probably any debian derivatives.

It is also available in a [copr](https://copr.fedorainfracloud.org/coprs/emmanuelp/Aravis/) repository.

An AppImage is not planned, as this distribution method is dedicated to application installation, while Aravis is a development library. The viewer should be more seen as a debugging tool. [qarv](https://github.com/AD-Vega/qarv) is probably more useful to end users.

Cheers.
