### ISSUE TITLE
Change multicast settings

### ISSUE THREAD

**Issue by turowicz** [AravisProject/aravis#650]
Is it possible to use aravis (genicam api) to set the camera's Multicast to Enabled?

**Comment by EmmanuelP** [comment]
Hi @turowicz 

Aravis discourse instance is a better fit for this sort of question.

https://aravis-project.discourse.group/c/using-aravis/8

Please continue the discussion [there](https://aravis-project.discourse.group/t/change-multicast-settings/421).
