### ISSUE TITLE
Missing Gstreamer plugin

### ISSUE THREAD

**Issue by mberrezak** [AravisProject/aravis#660]
**Describe the bug**
After downloading the recent mingw package:
https://packages.msys2.org/package/mingw-w64-x86_64-aravis-gst?repo=mingw64

starting the viewer results in the following error:

$ /mingw64/bin/arv-viewer-0.8.exe
-------------------------------------------------
Gstreamer plugin 'videoflip' is missing.
Missing GStreamer video output plugin (autovideosink, gtksink or gtkglsink)
Check your gstreamer installation.

I receive the very same issue on macOS after building with ninja as described in the documentation, with even more missing plugins. I did everything as described in the documentation.

**To Reproduce**
Install or build on MacOS (current version) or Windows 11.

**Expected behavior**
The viewer starts

**Platform description:**
MacOS ARM M1 current version
Windows 11

**Comment by EmmanuelP** [comment]
Hi @mberrezak 

autovideosink, gtksink and gtkglsink plugins are bundled in gstreamer-plugins-good. Is this package installed in your system ? If so, another possible issue is gstreamer and aravis are installed differently, or the path to the gstreamer plugin is not know to aravis.

If you have successfully built the viewer by yourself, you may try to execute arv-viewer-0.8 from the build directory, which should work.

I'm closing this issue as it is not an Aravis one. Don't hesitate to reopen if you think there is something wrong in Aravis itself.

Thanks.
