### ISSUE TITLE
Configure buffer timeout for GST

### ISSUE THREAD

**Issue by turowicz** [AravisProject/aravis#675]
**Is your feature request related to a problem? Please describe.**
When operating a Machine Vision camera that is hardware triggered on an assembly line, when the production stops for more than 2 seconds, GST drops the connection due to a hardcoded timeout in the line: https://github.com/AravisProject/aravis/blob/main/gst/gstaravis.c#L45

**Describe the solution you'd like**
We would like to see a configuration option for the `aravissrc` for the timeout manipulation.

**Describe alternatives you've considered**
String replace the .c file and recompile the gst module.

**Comment by EmmanuelP** [comment]
Hi,

Thanks for the report. The issue is already reported here: #528
