### ISSUE TITLE
Starting acquisition causes latency on other tasks

### ISSUE THREAD

**Issue by CFahrniBY** [AravisProject/aravis#682]
I am working with Aravis 0_8_2 with a GigE-camera and processing ~1ms data events from a PCIe adapter in parallel threads.
Once I reinitialize the camera with `arv_camera_create_stream` all other thread events are ignored --> No PCIe data is processed for approx. 270ms.

I now switched to RT priorities (-1 .. -49) - but it did not improve the lag.

Kernel: 5.4.74-rt41-amd64

Is there a known fix or should I update to a newer tag?

**Comment by EmmanuelP** [comment]
Hi @CFahrniBY 

There is not enough informations in your message to understand what is exactly the issue. Aravis threads should not mess with other threads (Well, not more than any other threads running on your system).

I'm closing this issue as this not seem Aravis is at fault. But feel free to reopen if you have more infos or even better a sample code that exhibits your issue.
