### ISSUE TITLE
Can't change framerate in camera viewer

### ISSUE THREAD

**Issue by tpwrules** [AravisProject/aravis#683]
**Describe the bug**
I cannot change the framerate of my camera using the option in the viewer.

**To Reproduce**
1. Open viewer
2. Start acquiring from camera
3. Open acquisition settings window
4. Type in new framerate in box
5. Observe that the old framerate remains and the framerate does not change

**Expected behavior**
I expected the value I typed in to stay in the box and the framerate shown in the status bar to change to that value.

**Camera description:**
 - Manufacturer: Allied Vision
 - Model: Alvim 1800 U-511m
 - Interface: USB3

**Platform description:**
 - Aravis version: 0.8.21 / main branch
 - OS: Ubuntu 20.04
 - Hardware: x86_64

**Additional context**
I've tracked this problem down to the fact that the camera does not allow the trigger mode to be written to when acquisition is active. If I patch out this call, everything works fine:
https://github.com/AravisProject/aravis/blob/baf2c63db00abc8aaa421dac4afcb06b915581e0/src/arvcamera.c#L977

**Comment by EmmanuelP** [comment]
Fixed in main. Thanks.
