### ISSUE TITLE
Auto negotiation of packet size doesn't seem to working all the time

### ISSUE THREAD

**Issue by ebfarias** [AravisProject/aravis#718]
**Describe the bug**
Aravis seems to use a wrong size for IP-layer headers, this lets any reception of test-packets fail.
The auto negotiation never test for packet sizes above the starting value.

**Expected behavior**
Expect auto negotiation to always pick the greatest packet size available. Unless of course it's turned off by the user. 

**Camera description:**
 - Manufacturer  SICK
 - Model Visionary-S CX V3S102-1x
 - Interface:  GigE

**Platform description:**
 - Aravis version 0.8.23
 - OS: Ubuntu 18.04
 - Hardware x86_64

**Additional context**
This also happens on other cameras like the Omron SENTECH-STC-MCS500POE-21HM319 and Basler-acA2040-25gc-22094718.
I've attached the changes made to allow this to work.
[aravischanges.txt](https://github.com/AravisProject/aravis/files/9566049/aravischanges.txt)

**Comment by EmmanuelP** [comment]
Hi,

Thanks for your report. Could you open a merge request with your changes ? It makes the review easier, and you will properly credited once the change will be merged.

**Comment by ebfarias** [comment]
It's not possible for me to open a merge request because of work constraints.

**Comment by EmmanuelP** [comment]
Please try #723
