### ISSUE TITLE
Please be more specific regarding installation in UBUNTU

### ISSUE THREAD

**Issue by helarsen** [AravisProject/aravis#727]
On page: [https://aravisproject.github.io/aravis/building.html](https://aravisproject.github.io/aravis/building.html)
there is a note about installation in UBUNTU:

_On some platforms (like Ubuntu), you may have to configure the dynamic linker (ld) to let it know where the aravis libraries are installed, and run ldconfig as root in order to update ld cache._

For inexperienced users, this is a rather cryptic instruction. Would it be suitable to be a bit more specific on this point to help those users (like myself)?

Unfortunately I am not able to suggest what to modify or add.
Thanks

**Comment by EmmanuelP** [comment]
Thanks for the report.

I have added the command to run in the documentation.

I understand some instructions may seem cryptic, but Aravis being a development library first, there is a minimum prerequisite knowledge. Learning this base knowledge is out of the scope of Aravis documentation.

Cheers.
