### ISSUE TITLE
Include COPYING.LESSER if licenced under the LGPL

### ISSUE THREAD

**Issue by quigybo** [AravisProject/aravis#74]
According to my reading of [how to use the LGPL](https://www.gnu.org/licenses/gpl-howto.html), LGPL-licensed projects should include a copy of both the GPL licence and the [LGPL licence](https://www.gnu.org/licenses/lgpl.txt), _usually in a file called COPYING.LESSER_.

**Comment by EmmanuelP** [comment]
I think that only applies to version 3 of the LGPL.

Please reopen if you think I'm wrong.

Thanks.

**Comment by quigybo** [comment]
I don't see any mention of the requirement in the [LGPL-v2.0 page](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html#SEC4), so I am going to tentatively (IANAL) agree with you. Cheers.
