### ISSUE TITLE
Adapt to Meson v1.0

### ISSUE THREAD

**Issue by mshr-h** [AravisProject/aravis#748]
The Meson team released [v1.0.0](https://github.com/mesonbuild/meson/releases/tag/1.0.0). There's room for improvement.

- replace `meson build` with `meson setup build` in [the docs of Installation section](https://aravisproject.github.io/aravis/building.html#installing-aravis) because the latter is preferred. See [Running Meson](https://mesonbuild.com/Running-Meson.html#configuring-the-build-directory).
- update the Meson version in [Travis ci script](https://github.com/AravisProject/aravis/blob/main/.travis.yml#L43).
  - I don't know why you stick with 0.47. Maybe you had a problem and solved it by doing that in #405 ?

**Comment by EmmanuelP** [comment]
Thanks for the pull request.

The travis configuration is obsolete, we are using github actions now.
