### ISSUE TITLE
Blank screen on viewer with FLIR BFS PGE 13Y3C

### ISSUE THREAD

**Issue by ashnarayan13** [AravisProject/aravis#75]
The Blackfly S cameras are detected and the images are sometimes visualized else I get a blank viewer. 
I am using the Aravis from the git repo
Any fix for it?

**Comment by EmmanuelP** [comment]
What platform ?

What is the console output of `arv-viewer -d all:3` ?

**Comment by EmmanuelP** [comment]
Which protocol ? GigeVision or USB3Vision ?

**Comment by fabio-d** [comment]
Hello,
I am dealing with the same problem using a TX2, so ARM64 platform.
The camera is USB3 and attached you can find the console output.
Using x86_64 it works as expected, if you need the console output let me know.
Thanks
![arv-viewer](https://user-images.githubusercontent.com/5803506/27648619-75464a8a-5c2f-11e7-887a-2ea8ac38ab86.png)
[13Y3C.txt](https://github.com/AravisProject/aravis/files/1109427/13Y3C.txt)

**Comment by EmmanuelP** [comment]
There was a number of fixes in the USB3Vision support since this report. I'm closing it. Please reopen if the issue still persist.

Thanks. Cheers.
