### ISSUE TITLE
Does this project offer paid services for customized feature development?

### ISSUE THREAD

**Issue by sdwhfx** [AravisProject/aravis#772]
1. Does this project accept donations?
2. Does this project offer paid services for customized feature development?

**Comment by EmmanuelP** [comment]
Hi,

Thanks for your interest in Aravis.

> 1. Does this project accept donations?

Yes !

https://opencollective.com/aravis-project

>     2. Does this project offer paid services for customized feature development?

No, but you may post a message in the community topic on Aravis Discourse instance:

https://aravis-project.discourse.group/c/community/7

Cheers,

  Emmanuel.
