### ISSUE TITLE
Is there a more efficient alternative interface than arv_stream_pop_buffer()?

### ISSUE THREAD

**Issue by Junkai-Liu** [AravisProject/aravis#776]
I run gige protocal camera in the xavier，the arv_stream_pop_buffer(). cost 8ms,Can you give me some suggestions to get a frame of data stream with a smaller delay.Below is my code，do you have any suggestions to optimize?
my camera set singelFrame mode.

```c
while(true)
{
     arv_stream_push_buffer(stream,arv_buffer_new(payload,NULL));
     arv_camera_start_acquisition(camera,&local_error);
     buffer = arv_stream_pop_buffer(stream);
}
```

**Platform description:**
 - Aravis version  0.8
 - OS: ubuntu18.04
 - Hardware  aarch64

**Comment by EmmanuelP** [comment]
There is no alternative to `arv_stream_pop_buffer()`, aravis uses an asynchronous queue as a circular storage for the buffers.
