### ISSUE TITLE
Python APIs are working but, making executable using pyinstaller not working

### ISSUE THREAD

**Issue by WeaponXI** [AravisProject/aravis#789]
**Describe the bug**
1. Python APIs are working as expected. I am able to open camera, stream and get data. But I want to make it a single package as I need some customization before displaying it. I tried "pyinstaller" module in python but not working.
**To Reproduce**
1. Build Aravis as given here: https://aravisproject.github.io/aravis/building.html
2. go to aravis/tests/python directory
3. Run any of the python file using: python <file>.py. It is running successfully.
4. Install pyinstaller: pip install pyinstaller
5. Make executable any of the file. For example:
   - pyinstaller --onefile arv-buffer-test.py
   - go to dist folder
   - run arv-buffer-test
   - It crashes and gives following error output:
 """
File "arv-buffer-test.py", line 13, in <module>
  File "gi/__init__.py", line 126, in require_version
ValueError: Namespace Aravis not available
[15160] Failed to execute script 'arv-buffer-test' due to unhandled exception!

"""

**Expected behavior**
It should print buffer counts as : 1

**Camera description:**
 - Manufacturer
 - Model
 - Interface [e.g. USB3]

**Platform description:**
 - Aravis version: 0.8.26
 - OS: Ubuntu 20.04
 - Hardware: [ x86_64]

**Additional context**
It seems that some dynamic linking issue with the lib. Any help !!

**Comment by EmmanuelP** [comment]
Hi @WeaponXI 

Thanks for the report. Unfortunately, you won't find much support for pyinstaller here. It seems gobject intropsection based python bindings are supported by pyinstaller, so you should try to ask the pyinstaller community about this issue.

I'm closing this issue as there is not much we can do in Aravis. Don't hesitate to reopen it if you think there is something that needs a fix.

Cheers.
