### ISSUE TITLE
Get APIs in python which can query same as arv-tool-0.8.exe

### ISSUE THREAD

**Issue by WeaponXI** [AravisProject/aravis#792]
When I run arv-tool-0.8.exe in MSYS2, it prints messages about connected camera and its features supported. Where I can find those APIs in python?

Messages: When run  arv-test-0.8.exe
Found 3 devices
Testing 'Cypress:FX3-0'
Genicam:Load                        SUCCESS
Genicam:Schema                      IGNORED
Properties:SensorSizeReadout        SUCCESS
Properties:SensorSizeCheck          IGNORED
Properties:GainAvailable            FAILURE
Properties:ExposureTimeAvailable    SUCCESS
Properties:ExposureTimeReadout      SUCCESS
MultipleAcquisitionA:BufferCheck    SUCCESS 10/10
MultipleAcquisitionA:FrameRate      FAILURE
SingleAcquisition:BufferCheck       SUCCESS
SoftwareTrigger:BufferCheck         SUCCESS 5/5
MultipleAcquisitionB:BufferCheck    FAILURE 0/10
MultipleAcquisitionB:FrameRate      FAILURE
Chunks:BufferCheck                  FAILURE OffsetX not found in available chunks

Plateform:
MSYS2 on WIndows 10

**Comment by EmmanuelP** [comment]
Hi,

The python API is built using gobject-introspection. All the aravis API used in [arvtool.c](https://github.com/AravisProject/aravis/blob/main/src/arvtool.c) should be available in python, so you should be able to reimplement the listing of camera features in python.

You will find the API generated by gobject-introspection in Aravis-0.8.gir. Don't hesitate to reopen if some API are missing in python.

Cheers.
