### ISSUE TITLE
Fake camera: User callback on read/write registers

### ISSUE THREAD

**Issue by abwitek** [AravisProject/aravis#797]
Hi!

**Is your feature request related to a problem? Please describe.**
More of an evolution than a fix.

**Describe the solution you'd like**
I'd like to be able to pass two function pointers to Arv Fake Camera (they would be stored inside *ArvFakeCameraPrivate* struct). *arv_fake_camera_read_memory* and *arv_fake_camera_write_memory* would then first each check whether their respective callback is set. If not, they'd go on with their current behavior, if so, replace that behavior if a call to user code.

This would permit a user (yay that's me!) to code a fake camera with programmable behavior on Genicam command reception. For example, a command that triggers a change somewhere else in memory *e.g.* an autofocus command that sets an arbitrary focus position value in another register.

**Describe alternatives you've considered**
Replacing library symbols on the fly with my own. But that's pretty evil.

**Additional context**
I'll do a fork/PR myself. Just want to know if there's interest on the dev's side before I go the extra mile to do a nice clean change instead of a quick and dirty hack.

**More additional context**
Thanks for this soft, helped me dodge a few shoot-self-in-the-foot bullets already.

**Comment by EmmanuelP** [comment]
Hi Alain,

Thanks for the proposal. I'm not too keen to complicate the fake camera code. It is mainly for testing the aravis GigEVision interface code. What would be interesting though is the implementation, in the fake camera, of GigEVision features like pending acknowledges or resent packets. This would improve our testing pipeline.

So your quick and dirty hack approach is fine, but don't hesitate to put your work in a published aravis fork, it could be of some interest to other aravis users.

Cheers.
