### ISSUE TITLE
EVK Helios support

### ISSUE THREAD

**Issue by anathesys** [AravisProject/aravis#815]
Please add support for EVK's Helios cameras by adding 

{ .vendor_selection = "EVK", .model_selection = "HELIOS"},

to the ArvGvLegacyInfos struct in arvgcport.c .

**Comment by anathesys** [comment]
Corresponding pull request added: https://github.com/AravisProject/aravis/pull/817

**Comment by EmmanuelP** [comment]
Merged. Thanks.
