### ISSUE TITLE
Wrong packet size with Basler GigE ACA640 on ARM RPi3

### ISSUE THREAD

**Issue by PhilippeDev** [AravisProject/aravis#85]
Aravis 0.5.9 has been installed on a Raspberry Pi 3 to drive a Basler GigE ACA640 camera. The camera is recognized, but an acquisition with arv-camera-test always returns a 0 Hz frame rate whatever is done in terms frame rate, gain and exposure. It seems there is an issue with the packet size which is wrongly evaluated.

Attached is the output of the command 'arv-camera-test -d all:3'.
[arv-camera-test-d-all3.txt](https://github.com/AravisProject/aravis/files/1155080/arv-camera-test-d-all3.txt)

**Comment by EmmanuelP** [comment]
There was a mistake that forced the packet size to -1 in arv-camera-test, but handled as unsigned int by ArvCamera, hence 65536.

That should be fixed in master.
