### ISSUE TITLE
I want an easy convert from aravis buffer to an OpenCV 4.X  Mat

### ISSUE THREAD

**Issue by JimXu1989** [AravisProject/aravis#864]
**Describe the solution you'd like**
I want an easy convert from aravis buffer convert to opencv Mat, in YUV442_8 or RGBPacked or other format.

**Comment by EmmanuelP** [comment]
Hi,

Thanks for your report.

Your request is out of the scope of Aravis. This project will not provide any image format converter, except for debugging purposes.

Cheers.
