### ISSUE TITLE
Enabling Auto Exposure 

### ISSUE THREAD

**Issue by RevanthVarma** [AravisProject/aravis#884]
I'm currently working on an autonomous robot project where we're using a Lucid camera for real-time video streaming. We're using the Aravis library for camera control, but I'm relatively new to using Aravis and still figuring things out.

Our goal is to enable auto exposure for the Lucid camera and perform some tuning to optimize the video streaming quality.
Any suggestions or guidance would be greatly helpful.

**Comment by EmmanuelP** [comment]
Aravis discord instance is a better place for question about how to uses Aravis.

[https://aravis-project.discourse.group/](https://aravis-project.discourse.group/)

About auto exposure, please refer to your device documentation. If your camera supports auto exposure, there should be a feature exposing this setting, you may be able to set using `arv_camera_set_(int|float|boolean)()`.
