### ISSUE TITLE
Gstreamer pipeline freeze on first frame (GStreamer + Daheng USB3)

### ISSUE THREAD

**Issue by glndti** [AravisProject/aravis#900]
**Describe the bug**
Only the first video frame is displayed, when a gstreamer pipeline is started. Note that arv-viewer-0.8 works as expected, showing a live video stream from the camera with the options to change relevant settings.

**To Reproduce**
Run a gstreamer pipeline, for instance:
gst-launch-1.0 aravissrc ! video/x-raw,format=GRAY8 ! videoconvert ! autovideosink

**Expected behavior**
A live rendering showing the output from the camera.

**Camera description:**
- Manufacturer: Daheng
- Model: VEN-505-36U3M-M05
- Interface: USB3

**Platform description:**
- Aravis version: 0.8.31
- OS: Ubuntu 20.04.6 LTS
- Hardware: x86_64

**Additional context**
A gstreamer test pipeline works as expected:
gst-launch-1.0 videotestsrc ! videoconvert ! autovideosink

A gstreamer test pipeline with a traditional camera with v4l2 that works as expected:
gst-launch-1.0 v4l2src device=/dev/video0 ! videoconvert ! autovideosink

Output from arv-test-0.8: [arv-test_output.txt](https://github.com/AravisProject/aravis/files/15233302/arv-test_output.txt)

Output from arv-test-0.8 genicam:  [genicam_info.txt](https://github.com/AravisProject/aravis/files/15233303/genicam_info.txt)

Output from gstreamer pipeline with ARV_DEBUG=all:2(info) and ARV_DEBUG=all:3(debug): 
[gstreamer_pipeline_aravis=info.txt](https://github.com/AravisProject/aravis/files/15233306/gstreamer_pipeline_aravis.info.txt)
[gstreamer_pipeline_aravis=debug.txt](https://github.com/AravisProject/aravis/files/15233305/gstreamer_pipeline_aravis.debug.txt)

Output from gstreamer pipeline with GST_DEBUG=3(fixme), GST_DEBUG=4(info) and GST_DEBUG=5(debug):
[gstreamer_pipeline_gst=debug.txt](https://github.com/AravisProject/aravis/files/15233309/gstreamer_pipeline_gst.debug.txt)
[gstreamer_pipeline_gst=fixme.txt](https://github.com/AravisProject/aravis/files/15233310/gstreamer_pipeline_gst.fixme.txt)
[gstreamer_pipeline_gst=info.txt](https://github.com/AravisProject/aravis/files/15233311/gstreamer_pipeline_gst.info.txt)

**Comment by EmmanuelP** [comment]
Try to explicitely define the framerate. Here is an example:

```
gst-launch-1.0 aravissrc ! video/x-raw,format=GRAY8,framerate=10/1 ! videoconvert ! autovideosink
```

Ensure you set a valid framerate for your camera.

**Comment by EmmanuelP** [comment]
No update? I'm closing the issue.

Don't hesitate to reopen it once you have the requested informations.

Thanks.
