### ISSUE TITLE
Is there a way to get the interface that is connected to the camera (or its IP/subnet)

### ISSUE THREAD

**Issue by jonahjjameson** [AravisProject/aravis#910]
I am using a setup where a single camera is connected to a computer with multiple 10Gige network interfaces.
I am looking for a way to get the interface name (i.e. eth0/enp4s0). 
Or if the name is not possible, get the IP or Subnet of the interface.

Is that something that is currently available in the api?

**Comment by EmmanuelP** [comment]
Hi,

There is <https://aravisproject.github.io/aravis/aravis-stable/method.GvDevice.get_interface_address.html>.

Please reopen the issue if this does fulfill your needs.
