### ISSUE TITLE
pValueIndexed support

### ISSUE THREAD

**Issue by EmmanuelP** [AravisProject/aravis#93]
Aravis lacks support for pValueIndexed, needed for Teledyne Dalsa Nano cameras.

This element is described page 33 and 36 of Genicam Standard 2.1.1

**Comment by sputnick1124** [comment]
I will not be very available in the coming months for testing fixes with this camera, but will try to pass the project off to others in my lab. Feel free to reach out if needed and I can request that they do some testing and join the conversation here.

**Comment by EmmanuelP** [comment]
@sputnick1124 support for pValueIndexed is in master.

I don't have a device that requires this feature, which means I can not test it for real. But I have added some tests in the test suite.

**Comment by sputnick1124** [comment]
I will try to test by the end of the week and add details to https://github.com/AravisProject/aravis/wiki/TestedCameras for documentation.
