### ISSUE TITLE
Teledyne Dalsa Genie Nano C2020 offset error

### ISSUE THREAD

**Issue by Fabio81x** [AravisProject/aravis#95]
Hello
we are starting to use Aravis to acquire an image from a Teledyne DALSA GigE camera on nvidia TX2. 
I dowloaded aravis "intswissknife" because the errors described in other posts (payload int error) and seems to work all but the offsets. 
If I set the offsets with the command arv_camera_set_region() with offsets different than 0, the stream returns that the buffers have TIMOUT error. Could this be an Aravis problem or a camera problem? 

What we do is run the example program (aravis wiki), print the status of the buffer (in the callback). We also check that the feature is set after the closing of the example program with "arv-tool-0.6 control OffsetX" and we see that the parameter is right. We use Width 320, Height 128, OffsetX 640, OffsetY 512.

Thanks for the help

**Comment by EmmanuelP** [comment]
> I dowloaded aravis "intswissknife" because the errors described in other posts (payload int error) and seems to work all but the offsets.

The code in this branch has been merged into master.

> If I set the offsets with the command arv_camera_set_region() with offsets different than 0, the stream returns that the buffers have TIMOUT error. Could this be an Aravis problem or a camera problem?
> What we do is run the example program (aravis wiki), print the status of the buffer (in the callback).

Could you attach the console output when your test is running with ARV_DEBUG environment variable set to 'thread:3,stream-thread:3' ?

**Comment by IamSierraCharlie** [comment]
Hi! Just as another point of interest, does the camera come with its own propriety software?  If so, what happens when you apply the same offset / settings in that software?  If the offset works in the cameras propriety software, then it might suggest an aravis issue, otherwise; if not, then something at play on the camera side?  In my experience, I always found it useful to compare capabilities.  Admittedly the camera I use is different to yours.

**Comment by Fabio81x** [comment]
Hello to all

1) here there is the log

Command:
`ARV_DEBUG=thread:3,stream-thread:3 ./GigeVision`

LOG:
_[GvStream::stream_thread] Packet timeout = 40 ms
[GvStream::stream_thread] Frame retention = 200 ms
[GvStream::find_frame_data] Start frame 1
[GvStream::process_packet] Error packet at dt = 49, packet id = 1 frame id = 1
[GvStream::find_frame_data] Start frame 2
[GvStream::missing_packet_check] Resend request at dt = 40285, packet id = 54/55
[GvStream::send_packet_request] frame_id = 2 (23 - 54)
[GvStream::missing_packet_check] Resend request at dt = 80621, packet id = 54/55
[GvStream::send_packet_request] frame_id = 2 (23 - 54)
[GvStream::missing_packet_check] Resend request at dt = 120899, packet id = 54/55
[GvStream::send_packet_request] frame_id = 2 (23 - 54)
[GvStream::missing_packet_check] Resend request at dt = 161153, packet id = 54/55
[GvStream::send_packet_request] frame_id = 2 (23 - 54)
[GvStream::check_frame_completion] Timeout for frame 1 at dt = 217999
Frame Error, status: 2
[GvStream::close_frame] Close frame 1
[GvStream::check_frame_completion] Timeout for frame 2 at dt = 201433
Frame Error, status: 2
[GvStream::close_frame] Close frame 2
Frame rate = 0 Hz
Frame rate = 0 Hz
Frame rate = 0 Hz
Frame rate = 0 Hz
Frame rate = 0 Hz_


2) Yes, with the camera own sw (Sapera) seems that we can change the offsets ant the image comes right, but only in windows form not on linux systems.

Other informations:

- It seems that the first time you try to run the sw, the offsets did not affect the capture and it works. If i run the `arv-tool-0.6 control OffseX` I found a value of 0 instead 640. The other times the camera goes wrong (and sometimes chrashes, I have to power off and on the camera, with the arv-tool-0.6 I can't find it). If I run the test `arv-tool-0.6 control OffseX` after the second time i see the right offsets set.

- I also tried to set with 2 different code lines the dimension of the images (forst) wth offsets to 0 and than to set the offsets (with the same image)

        arv_camera_set_region (camera, 0, 0, 320, 128);
        arv_camera_set_region (camera, 640, 512, 320, 128);

I found that the first time you run the code (after power reset of the camera) the problem occours. 
LOG:
_[GvStream::stream_thread] Packet timeout = 40 ms
[GvStream::stream_thread] Frame retention = 200 ms
[GvStream::find_frame_data] Start frame 1
[GvStream::process_packet] Error packet at dt = 53, packet id = 1 frame id = 1
[GvStream::find_frame_data] Start frame 2
[GvStream::process_packet] Error packet at dt = 33, packet id = 1 frame id = 2
[GvStream::find_frame_data] Start frame 3
[GvStream::process_packet] Error packet at dt = 36, packet id = 1 frame id = 3
[GvStream::find_frame_data] Start frame 4
[GvStream::process_packet] Error packet at dt = 28, packet id = 1 frame id = 4
[GvStream::find_frame_data] Start frame 5
[GvStream::process_packet] Error packet at dt = 25, packet id = 1 frame id = 5
[GvStream::check_frame_completion] Timeout for frame 1 at dt = 240122
Frame Error, status: 2
[GvStream::close_frame] Close frame 1
[GvStream::find_frame_data] Start frame 6
[GvStream::check_frame_completion] Timeout for frame 2 at dt = 200052
Frame Error, status: 2
[GvStream::close_frame] Close frame 2
[GvStream::process_packet] Error packet at dt = 218, packet id = 1 frame id = 6
[GvStream::find_frame_data] Start frame 7
[GvStream::check_frame_completion] Timeout for frame 3 at dt = 200095
Frame Error, status: 2
[GvStream::close_frame] Close frame 3
[GvStream::process_packet] Error packet at dt = 208, packet id = 1 frame id = 7
[GvStream::find_frame_data] Start frame 8
[GvStream::check_frame_completion] Timeout for frame 4 at dt = 200044
Frame Error, status: 2
[GvStream::close_frame] Close frame 4
[GvStream::process_packet] Error packet at dt = 213, packet id = 1 frame id = 8
[GvStream::find_frame_data] Start frame 9
[GvStream::check_frame_completion] Timeout for frame 5 at dt = 200052
Frame Error, status: 2
[GvStream::close_frame] Close frame 5
[GvStream::process_packet] Error packet at dt = 200, packet id = 1 frame id = 9
[GvStream::find_frame_data] Start frame 10
[GvStream::process_packet] Error packet at dt = 97, packet id = 1 frame id = 10
[GvStream::check_frame_completion] Timeout for frame 6 at dt = 240293
Frame Error, status: 2
[GvStream::close_frame] Close frame 6
[GvStream::find_frame_data] Start frame 11
[GvStream::process_packet] Error packet at dt = 87, packet id = 1 frame id = 11
[GvStream::check_frame_completion] Timeout for frame 7 at dt = 240290
Frame Error, status: 2
[GvStream::close_frame] Close frame 7
[GvStream::find_frame_data] Start frame 12
[GvStream::process_packet] Error packet at dt = 86, packet id = 1 frame id = 12
[GvStream::check_frame_completion] Timeout for frame 8 at dt = 240331
Frame Error, status: 2
[GvStream::close_frame] Close frame 8
[GvStream::find_frame_data] Start frame 13
[GvStream::process_packet] Error packet at dt = 80, packet id = 1 frame id = 13
[GvStream::check_frame_completion] Timeout for frame 9 at dt = 240260
Frame Error, status: 2
[GvStream::close_frame] Close frame 9
[GvStream::find_frame_data] Start frame 14
[GvStream::process_packet] Error packet at dt = 80, packet id = 1 frame id = 14
[GvStream::check_frame_completion] Timeout for frame 10 at dt = 200107
Frame Error, status: 2
[GvStream::close_frame] Close frame 10
[GvStream::find_frame_data] Start frame 15
[GvStream::process_packet] Error packet at dt = 81, packet id = 1 frame id = 15
[GvStream::check_frame_completion] Timeout for frame 11 at dt = 240197
Frame Error, status: 2
[GvStream::close_frame] Close frame 11
[GvStream::find_frame_data] Start frame 16
[GvStream::process_packet] Error packet at dt = 87, packet id = 1 frame id = 16
[GvStream::check_frame_completion] Timeout for frame 12 at dt = 240221
Frame Error, status: 2
[GvStream::close_frame] Close frame 12
[GvStream::find_frame_data] Start frame 17
[GvStream::process_packet] Error packet at dt = 81, packet id = 1 frame id = 17
[GvStream::check_frame_completion] Timeout for frame 13 at dt = 200115
Frame Error, status: 2
[GvStream::close_frame] Close frame 13
[GvStream::find_frame_data] Start frame 18
[GvStream::process_packet] Error packet at dt = 80, packet id = 1 frame id = 18
[GvStream::check_frame_completion] Timeout for frame 14 at dt = 240215
Frame Error, status: 2
[GvStream::close_frame] Close frame 14
[GvStream::find_frame_data] Start frame 19
[GvStream::process_packet] Error packet at dt = 83, packet id = 1 frame id = 19
[GvStream::check_frame_completion] Timeout for frame 15 at dt = 200118
Frame Error, status: 2
[GvStream::close_frame] Close frame 15
[GvStream::find_frame_data] Start frame 20
[GvStream::process_packet] Error packet at dt = 87, packet id = 1 frame id = 20
[GvStream::check_frame_completion] Timeout for frame 16 at dt = 240221
Frame Error, status: 2
[GvStream::close_frame] Close frame 16
[GvStream::find_frame_data] Start frame 21
[GvStream::process_packet] Error packet at dt = 84, packet id = 1 frame id = 21
[GvStream::check_frame_completion] Timeout for frame 17 at dt = 240211
Frame Error, status: 2
[GvStream::close_frame] Close frame 17
[GvStream::find_frame_data] Start frame 22
[GvStream::process_packet] Error packet at dt = 82, packet id = 1 frame id = 22
[GvStream::check_frame_completion] Timeout for frame 18 at dt = 200112
Frame Error, status: 2
[GvStream::close_frame] Close frame 18
[GvStream::find_frame_data] Start frame 23
[GvStream::process_packet] Error packet at dt = 79, packet id = 1 frame id = 23
[GvStream::check_frame_completion] Timeout for frame 19 at dt = 240212
Frame Error, status: 2
[GvStream::close_frame] Close frame 19
[GvStream::find_frame_data] Start frame 24
[GvStream::process_packet] Error packet at dt = 78, packet id = 1 frame id = 24
[GvStream::check_frame_completion] Timeout for frame 20 at dt = 200099
Frame Error, status: 2
[GvStream::close_frame] Close frame 20
[GvStream::find_frame_data] Start frame 25
[GvStream::process_packet] Error packet at dt = 101, packet id = 1 frame id = 25
[GvStream::check_frame_completion] Timeout for frame 21 at dt = 200096
Frame Error, status: 2
[GvStream::close_frame] Close frame 21
[GvStream::find_frame_data] Start frame 26
[GvStream::process_packet] Error packet at dt = 85, packet id = 1 frame id = 26
[GvStream::check_frame_completion] Timeout for frame 22 at dt = 240232
Frame Error, status: 2
[GvStream::close_frame] Close frame 22
[GvStream::find_frame_data] Start frame 27
[GvStream::process_packet] Error packet at dt = 89, packet id = 1 frame id = 27
[GvStream::check_frame_completion] Timeout for frame 23 at dt = 200118
Frame Error, status: 2_


- the code I use is this. I only added:

> the printf information about the status of the buffer
> the dimensions of the image
> the stop signal before stop acquisition camera

#include <arv.h>
#include <stdlib.h>
#include <signal.h>
#include <stdio.h>

typedef struct {
    GMainLoop *main_loop;
    int buffer_count;
} ApplicationData;

static gboolean cancel = FALSE;

static void
set_cancel (int signal)
{
    cancel = TRUE;
}

static void
new_buffer_cb (ArvStream *stream, ApplicationData *data)
{
    ArvBuffer *buffer;

    buffer = arv_stream_try_pop_buffer (stream);
    if (buffer != NULL) {

    	ArvBufferStatus status;
        if ((status = arv_buffer_get_status (buffer)) == ARV_BUFFER_STATUS_SUCCESS)
            data->buffer_count++;
        else
        	{
         	     printf("Frame Error, status: %d\n", status);
        	}
        /* Image processing here */
        arv_stream_push_buffer (stream, buffer);
    }
}

static gboolean
periodic_task_cb (void *abstract_data)
{
    ApplicationData *data = abstract_data;

    printf ("Frame rate = %d Hz\n", data->buffer_count);
    data->buffer_count = 0;

    if (cancel) {
        g_main_loop_quit (data->main_loop);
        return FALSE;
    }

    return TRUE;
}

static void
control_lost_cb (ArvGvDevice *gv_device)
{
    /* Control of the device is lost. Display a message and force application exit */
    printf ("Control lost\n");

    cancel = TRUE;
}

int
main (int argc, char **argv)
{
    ApplicationData data;
    ArvCamera *camera;
    ArvStream *stream;
    int i;

    data.buffer_count = 0;

    /* Mandatory glib type system initialization */
    arv_g_type_init ();

    /* Instantiation of the first available camera */
    camera = arv_camera_new (NULL);

    if (camera != NULL) {
        void (*old_sigint_handler)(int);
        gint payload;

        /* Set region of interrest to a 200x200 pixel area */
        arv_camera_set_region (camera, 640, 512, 320, 128);

        /* Set frame rate to 10 Hz */
        arv_camera_set_frame_rate (camera, 20.0);

        /* retrieve image payload (number of bytes per image) */
        payload = arv_camera_get_payload (camera);

        /* Create a new stream object */
        stream = arv_camera_create_stream (camera, NULL, NULL);
        if (stream != NULL) {
            /* Push 50 buffer in the stream input buffer queue */
            for (i = 0; i < 50; i++)
                arv_stream_push_buffer (stream, arv_buffer_new (payload, NULL));

            /* Start the video stream */
            arv_camera_start_acquisition (camera);

            /* Connect the new-buffer signal */
            g_signal_connect (stream, "new-buffer", G_CALLBACK (new_buffer_cb), &data);
            /* And enable emission of this signal (it's disabled by default for performance reason) */
            arv_stream_set_emit_signals (stream, TRUE);

            /* Connect the control-lost signal */
            g_signal_connect (arv_camera_get_device (camera), "control-lost",
                      G_CALLBACK (control_lost_cb), NULL);

            /* Install the callback for frame rate display */
            g_timeout_add_seconds (1, periodic_task_cb, &data);

            /* Create a new glib main loop */
            data.main_loop = g_main_loop_new (NULL, FALSE);

            old_sigint_handler = signal (SIGINT, set_cancel);

            /* Run the main loop */
            g_main_loop_run (data.main_loop);

            signal (SIGINT, old_sigint_handler);

            g_main_loop_unref (data.main_loop);

            /* And disable emission of this signal */
            arv_stream_set_emit_signals (stream, FALSE);

            /* Stop the video stream */
            arv_camera_stop_acquisition (camera);

            g_object_unref (stream);
        } else
            printf ("Can't create stream thread (check if the device is not already used)\n");

        g_object_unref (camera);
    } else
        printf ("No camera found\n");

    return 0;
}

**Comment by EmmanuelP** [comment]
What gives `arv-tool-0.6 -d evaluator:3,genicam:3,device:3 control Width=320 Height=128 OffsetX=640 OffsetY=512 Width Height OffsetX OffsetY` when streaming fails ?

**Comment by EmmanuelP** [comment]
No update, old report. I'm closing this issue. Please reopen if you have the requested informations.

Thanks.
