### ISSUE TITLE
BAYER10 format is not supported

### ISSUE THREAD

**Issue by Rz-Rz** [AravisProject/aravis#952]
**Is your feature request related to a problem? Please describe.**
My camera is outputting a BAYER10 streams but aravis detects it as a mono10. 

**Describe the solution you'd like**
It would be nice if it could correctly parse it, in the viewer etc. It would be nice to be able to simulate a BAYER10 streams aswell using the fake camera.

**Describe alternatives you've considered**
Using GStreamer to produce a BAYER10 streams to test with it?

**Comment by EmmanuelP** [comment]
What does tell you aravis detects bayer10 as mono10 ?

**Comment by Rz-Rz** [comment]
It's the viewer that automatically capture the stream as mono10, and I can't seem to set it as BAYER10

**Comment by EmmanuelP** [comment]
Ah ok. That is because gstreamer does not support bayer10 (at least the last time I checked). arv-viewer picks the first supported pixel format. I'm not willing to add pixel fomat conversion in aravis, it is out of the scope of this library.

Cheers.

**Comment by EmmanuelP** [comment]
That being said, the day gstreamer supports bayer10, I will happily add the support for it in arv-viewer.
