### ISSUE TITLE
Python Segmentation Fault when calling Aravis.Camera.new(None) 

### ISSUE THREAD

**Issue by questions-mark** [AravisProject/aravis#953]
**Describe the Bug** 
Calling `Aravis.Camera.New(None)` without a camera connected results in a segmentation fault. 
This happends with Aravis Version 0.10, but not with version 0.8. 

**To Reproduce** 
```Python 
import gi 
produce_segfault = True 
if produce_segfault: 
    gi.require_version("Aravis", "0.10") 
else: 
    gi.require_version("Aravis", "0.8") 
from gi.repository import Aravis 

if __name__ == "__main__": 
    Aravis.update_device_list() 
    assert Aravis.get_n_devices() == 0
    camera = Aravis.Camera.new(None)
```

**Expected behavior**
Exception occuring

**Camera description:**
 - Manufacturer: Flir
 - Model: BFLY-PGE-50S5M
 - Interface: Ethernet

**Platform description:**
 - Aravis version: 0.10 
 - OS: Ubuntu 22.04.1 (Kernel Version 6.5.0-45)
 - Hardware: x86_64 (VirtualBox Virtual Machine)

**Additional context**
Calling `Aravis.Camera.new(some_ip)' with an IP address, an exception is thrown as expected.

**Comment by EmmanuelP** [comment]
Hi, thanks for the report.

Please try #953
