### ISSUE TITLE
Adapting old code written for Gige to work with USB3

### ISSUE THREAD

**Issue by hdevillepoix** [AravisProject/aravis#99]
Trying to adapt some code that was written to talk to Gige cameras through Aravis (written for Aravis 0.3 or 0.4), to make it compatible with a USB3 camera (Point Grey blackfly).

Have a function that was calling `arv_gv_interface_get_instance`, so naturally I want to try to call `arv_uv_interface_get_instance` for USB3 cameras. But it is not accessible, because presumably `ARAVIS_BUILD_USB` is not set, even though I got `Build USB support:            yes` on the ./configure

Sorry I'm new to this, so this might be a silly question that just reflects how little I understand how the whole thing is supposed to work :P

**Comment by EmmanuelP** [comment]
I have pushed a fix to master that fixes the inclusion of usb3 headers in arv.h.

The recommended way to instantiate devices is to use the ArvCamera API.

Thanks for the report.
